### ISSUE TITLE
not recognised by hearthstone deck tracker

### ISSUE THREAD

**Issue by sebzeppelin** [rembound/Arena-Helper#10]
I've extracted the Arena Helper folder to Program files (x86) > Hearthstone Deck Tracker > Plugins.  I've clicked Unblock on the Arena Helper dll and all the other dll's but still not recognised by HDT. Whenever I right click on a dll after all this the Unblock button is still available to be pressed.

**Comment by mrapp** [comment]
Did you click "ok" or "apply" before closing the dialog? (I know it sounds stupid but I made this mistake a couple time before realizing what was going on.)

**Comment by sebzeppelin** [comment]
yes I did

**Comment by rembound** [comment]
Make sure the ArenaHelper directory is inside the Plugins directory, and inside the ArenaHelper directory, is the ArenaHelper.dll. Maybe the ArenaHelper directory is in another Directory inside the Plugins directory. HDT only allows plugins to be in one subdirectory only.

**Comment by sebzeppelin** [comment]
Yes the path is C:\Program Files (x86)\Hearthstone Deck Tracker\Plugins\ArenaHelper, with all the dll's and subfolders inside that.  It is missing the MSVCP110.dll but I've repaired the visual C++ files as advised in the readme and still can't get it to work.

**Comment by Alkyno** [comment]
Hi man, I had the same issue.
You have to make sure that ArenaHelper.dll is unblocked, it worked for me.
"If the Plugin does not show up in that list, rightclick the [PLUGINNAME].dll, go into Properties and click "Unblock" at the bottom."
