### ISSUE TITLE
Auto-uptdade doesn't work

### ISSUE THREAD

**Issue by imapriestbro** [rembound/Arena-Helper#102]
Hi, i have a problem about the auto-update, i tried to reinstall some times but arena helper still not work. It doens't detect any card and doenst give any value ... I wanted to install it manually but i've no idea if i did it well or not.

Thanks for your help !

**Comment by rembound** [comment]
Check out issue https://github.com/rembound/Arena-Helper/issues/100 and the [How To Install](https://github.com/rembound/Arena-Helper#how-to-install) in the readme.
