### ISSUE TITLE
Arena Helper stuck on "Detecting Arena"

### ISSUE THREAD

**Issue by keld0rn** [rembound/Arena-Helper#104]
Print Screen showing the situation (with debug mode enabled):
http://prntscr.com/cihzlr

**Comment by gnu-lorien** [comment]
I'm in the same boat. Doesn't seem to be able to detect the arena anymore.

**Comment by panem-losu** [comment]
+
Install with instruction, but not work. Reinstall, restart, resolution change not help (

**Comment by rembound** [comment]
Fixed in new version, thanks for the reports!

**Comment by keld0rn** [comment]
Yes, the new version fixed my problem, thank you.
