### ISSUE TITLE
Detecting cards....cant detect

### ISSUE THREAD

**Issue by wetshrimp** [rembound/Arena-Helper#105]
was using an older version. everything updated autmatically (hearthstone deck tracker, arena helper) and then i get stuck on detecting cards. downgraded to 0.80 helper like in one of the comments and still nothnig. ideas?

**Comment by rembound** [comment]
You can try the version I attached to issue: https://github.com/rembound/Arena-Helper/issues/101
Downgrading will not work, because the use of visual hashes has changed.

**Comment by wetshrimp** [comment]
Thanks but still didn't work. 0.8.3 Right? Still stuck on detecting cards :(

**Comment by rembound** [comment]
Released the update. Don't know if it fixes it.
