### ISSUE TITLE
Tier List Update

### ISSUE THREAD

**Issue by ac9** [rembound/Arena-Helper#106]
New Tier List update on 2016-09-17
http://thelightforge.com/TierList/ChangeLog

Checked cardtier.json to make sure the data is invalid and Goblin Blastmage is 54 not 60.

**Comment by rembound** [comment]
Thanks for the report, but the tier list is actually updated. Check out my explanation here: https://github.com/rembound/Arena-Helper/issues/71#issuecomment-192608254

**Comment by ac9** [comment]
Must be an issue with my auto updater since the last modified date is 2016-09-24 but the data for Goblin Blastmage is 54 not 60. Is there anyway to trigger the update manually? I've tried reinstalling the plugin with removing the %APPDATA%\HearthstoneDeckTracker\ArenaHelper but it did not trigger a response.

Also, on a side note, tier list did get updated again today.

**Comment by rembound** [comment]
Arena Helper v0.8.4 already includes the tier list with Goblin Blastmage = 60, so don't know what happened. There is no manual way to update the tier list. The plugin connects to GitHub to check version information. Maybe it couldn't connect properly.

Just updated the tier list, you should be seeing the update message shortly.

**Comment by ac9** [comment]
Okay. Tier List looks like its now properly updated. Thanks.
