### ISSUE TITLE
Stopped drawing AH window

### ISSUE THREAD

**Issue by ShotFromGuns** [rembound/Arena-Helper#107]
The AH plug-in showed as updated today when I launched it. I used it once, and it did the another bug I've encountered before, where it freezes on the last card. I manually closed the AH window, which is my usual workaround for that.

When I started a new Arena run and re-opened the plugin, the values for the last set of cards would appear, but the AH window itself would not. In Task View, I could see the AH window drawn normally, but when selecting it from Task View or the taskbar, or tabbing into it to try to maximize it, the window did not display, and thus could not be interacted with to start a new Arena draft.

I uninstalled and reinstalled the plugin, and it's having the same problem again.

ArenaHelper v0.8.4 in HDT v1.1.2, on a Surface Pro 4 running Win10 Pro (64 bit).

Here you can see the AH window appears in Task View:

![hdt-ah_bug01](https://cloud.githubusercontent.com/assets/22432406/20813606/d9779156-b7db-11e6-9e81-52fc269c6a84.png)

Here you can see that it doesn't draw when it's selected:

![hdt-ah_bug02](https://cloud.githubusercontent.com/assets/22432406/20813547/9e528590-b7db-11e6-95a9-3e74308d6a13.png)

**Comment by rembound** [comment]
You could try deleting the latest deck file from the decks directory located in:
> %appdata%\HearthstoneDeckTracker\ArenaHelper\Decks

Deleting the entire ArenaHelper directory in appdata is also possible, but you will lose some settings and historic deck files.

**Comment by ShotFromGuns** [comment]
That fixed it! Looks like the reason it didn't work when I tried reinstalling before is I pulled the copy out of ~\HearthstoneDeckTracker\Plugins\ but not ~\HearthstoneDeckTracker\ itself. Thanks!
