### ISSUE TITLE
Request: Option to customize Arena deck name template

### ISSUE THREAD

**Issue by ShotFromGuns** [rembound/Arena-Helper#108]
I like to have all my Arena decks named so they'll sort properly by date and time. Instead of the current format of:

Arena DD-MM H:MM _(12 hr time)_

I'd like to be able to set mine to name my Arena decks as:

Arena YYYY-MM-DD HH:MM _(24-hr time)_

So, for example, a deck created at 2:30 p.m. on December 1st currently is named as **Arena 01-12 2:15**, and I would like to be able to set up the plug-in so that it would instead be automatically named **Arena 2016-12-01 14:30**.

**Comment by ShotFromGuns** [comment]
Scratch this: drafting an Arena deck with AH disabled, it still formats the name the same way, so I assume this is a function of HDT itself, not this plugin.

**Comment by riQQ** [comment]
Enable advanced options in HDT and go to `Options > Tracker > Importing > Arena Deck Name Template`.

**Comment by ShotFromGuns** [comment]
I never would have thought to look there--thank you!
