### ISSUE TITLE
Deck tracking during draft

### ISSUE THREAD

**Issue by corlettb** [rembound/Arena-Helper#11]
I'd like to integrate HDT and Arena Helper better and track the deck through HDT as the draft progresses.

This from a UI point of view just confirms to the user that his/her selections are being picked up correctly and removes the need to save the deck at the end of the draft. E.g. 

![decktracking](https://cloud.githubusercontent.com/assets/2338074/8129500/b3bce2d6-1101-11e5-9c32-b5acba1e0734.jpg)

I managed to get this working with the following Arena Helper change :

https://github.com/corlettb/Arena-Helper/commit/dd341d15158d5b5ead29594dcfa9fe5a8f644589

However... this also required changes to HDT. Making SaveDeck public and adding a bool so that on save if the deck contained less than 30 cards you wouldn't get the confirm dialog.

What do you think of this rembound? Do you think we can convince epix37 that plugins should be able to save decks inside HDT?

**Comment by rembound** [comment]
It looks like a nice feature, but detection is not flawless on all computers. I don't know if this is better than the current method. It does give the user immediate feedback, which is good. On the other hand, it makes the user experience potentially more complex. Users will check the list after every click. Of course, it could be added as an optional feature.

**Comment by corlettb** [comment]
They don't have to check every click. It just can give them that warm fuzzy feeling that things are working. You also don't need to go through that "Save" => "Save" => "Use" step at the end of the draft. Of course you want to save it :). The detection works flawlessly at least on my machine, but I know others have complained. 

Rather than a manual selection option wouldn't it be better for you to do a "Opps! I missed that selection" popup if all the cards have changed all of a sudden?

Of course it would be better if we could convince epix37 that we need a to be able to add a mouseclick call back.

**Comment by corlettb** [comment]
Should I try and add a feature request to HDT and see what epix37 says? or go straight in with a pull request?

**Comment by rembound** [comment]
Whatever you think is best. @Epix37 was pretty active here a couple of days ago.

**Comment by corlettb** [comment]
What a hero! epix37 merged it. Guess we have to wait for a release now :)

**Comment by corlettb** [comment]
Looks like we have a release with this in now :) So what do you think about adding this? we could add an option to disable auto save if you don't think everyone would want it.

**Comment by rembound** [comment]
I have been waiting for the new HDT release to implement this. Will be an optional feature for the next release.

**Comment by rembound** [comment]
Added to the repo, next release will be soon.
