### ISSUE TITLE
Missing .dll files

### ISSUE THREAD

**Issue by llcookj** [rembound/Arena-Helper#114]
I cannot add the plugin to HDT. Within the Arena-Helper-master directory neither ArenaHelper.dll nor MSVCP120.dll are showing up. Did I do something wrong when extracting?

Thanks
![arenahelper](https://cloud.githubusercontent.com/assets/8907346/24162506/20776ea6-0e3e-11e7-9e9c-9d1f0cf11e10.PNG)

**Comment by rembound** [comment]
You have downloaded the source code instead of the actual plugin. Make sure to download the ArenaHelper.vX.Y.Z.zip

Instructions can be found here: [How To Install](https://github.com/rembound/Arena-Helper#how-to-install)
