### ISSUE TITLE
Ridiculous values for all cards in Arena

### ISSUE THREAD

**Issue by goldenmane** [rembound/Arena-Helper#117]
There appears to be some bug after new update showing values exceeding 100 for some average cards. You can't tell me that what I see in the picture below is supposed to be correct.

![hs2](https://cloud.githubusercontent.com/assets/19500732/24837724/f77dc52a-1d3a-11e7-8616-b2fb8b71b87e.jpg)
![murloc](https://cloud.githubusercontent.com/assets/19500732/24837725/f77e4cde-1d3a-11e7-9e95-afd7f774cbf3.jpg)
![hs3](https://cloud.githubusercontent.com/assets/19500732/24837733/2856f220-1d3b-11e7-8b18-a9fd6dccafbf.jpg)

**Comment by QXD-me** [comment]
@goldenmane The tier list was re-centred around 100. 100 is now average

**Comment by goldenmane** [comment]
...very weird, but ok, thank you for explaining :)
