### ISSUE TITLE
Ratings of MSG multiclass cards

### ISSUE THREAD

**Issue by supertriodo** [rembound/Arena-Helper#119]
Hey,

You are doing an amazing job with this addon.

I'm the developer behind [Arena Tracker](https://github.com/supertriodo/Arena-Tracker) and would like to use your json to organize light forge ratings if you are ok with it.

I have find a little problem with MSG multiclass card that shows ratings for all 9 classes instead of only the 3 classes related.

An example:

  {
    "id": "CFM_853",
    "name": "Grimestreet Smuggler",
    "value": [
      "96",
      "96",
      "96",
      "96",
      "96",
      "96",
      "96",
      "96",
      "96"
    ]
  }

Keep up the good work!

**Comment by rembound** [comment]
I get the scores from the lightforge api at: `http://thelightforge.com/api/TierList/Latest?locale=enUS`

The `Grimestreet Smuggler` card actually has default score data as you can see below (`"Hero": null`). Other single-class cards don't have the default score, so it's an error within the lightforge tier list.
```
		"CardId": "CFM_853",
		"Cost": 3,
		"Hero": "Hunter",
		"Name": "Grimestreet Smuggler",
		"Names": null,
		"NewCard": false,
		"Rarity": "Common",
		"Scores": [{
			"Hero": null,
			"Score": 96.0,
			"StopAfterFirst": false,
			"StopAfterSecond": false
		},
		{
			"Hero": "Hunter",
			"Score": 96.0,
			"StopAfterFirst": false,
			"StopAfterSecond": false
		},
		{
			"Hero": "Paladin",
			"Score": 96.0,
			"StopAfterFirst": false,
			"StopAfterSecond": false
		},
		{
			"Hero": "Warrior",
			"Score": 96.0,
			"StopAfterFirst": false,
			"StopAfterSecond": false
		}]
```

Thanks!

**Comment by supertriodo** [comment]
Yep seems a bug on their end. Thanks for the info :)
