### ISSUE TITLE
Arena Deck Helper Crashes

### ISSUE THREAD

**Issue by ryan17** [rembound/Arena-Helper#12]
![crash arena helper](https://cloud.githubusercontent.com/assets/12861767/8132285/f46cc2fa-1120-11e5-88f1-c43501e67e73.png)

The Hearthstone Deck Tracker crashes after i focus hearthstone, i tried every resolution with and without the full screen mode, i run windows 7 ultimate 64 bit i thought that 64 bit could be the problem maybe cause in my net-book pc works just fine with windows 8.1 32 bit.

**Comment by rembound** [comment]
This is a strange problem. It seems the OpenCV library that my plugin depends on, crashes. When the program gets the focus, calls to the library are made.

I have Windows 7 Home Premium 64 bit, so that shouldn't be the problem.

After some searching I found that this crash might happen on [certain cpus](http://answers.opencv.org/question/35102/opencv-crash-c000001d-severe-problem-with-a-solution-proposal/). I don't know if there is a fix.

**Comment by Ksoucek** [comment]
Same PROBLEM here.. Intel i5- 4590 /  64bit win7 professional .. this program looks great.... i realy want to use it in my  HDT

**Comment by rembound** [comment]
I have added a version of the plugin with a newer, beta version of the OpenCV library [ArenaHelper.v0.2.1.zz.EmguCV3.zip](https://github.com/rembound/Arena-Helper/releases/download/0.2.1/ArenaHelper.v0.2.1.zz.EmguCV3.zip). I don't know if they have fixed their bug, but you can try it out.

**Comment by ryan17** [comment]
Ok with this version it doesn't crash anymore but it doesn't detect the heroes even if i spam new arena or change resolution, it is stack in detecting arena. I saw the other post about the detection problem but i don't know where is the  "-popupwindow" flag in the Hearthstone options you were talking about.

**Comment by n00neimp0rtant** [comment]
@rembound This plugin version (with the newer OpenCV lib) is no longer crashing, and appears to be working.

![untitled](https://cloud.githubusercontent.com/assets/170001/8145453/7009d0a0-11d6-11e5-9047-b03ca48e6a58.png)

@ryan17, I am not having any problems with deck detection.

**Comment by rembound** [comment]
Thanks for the feedback @n00neimp0rtant. I will use the newer lib for the next releases.

@ryan17: In another thread I have explained that you can enable a debug mode:
>You can enable some on-screen debug information by going to the AppData directory: >HearthstoneDeckTracker\ArenaHelper\ opening arenahelper.json and modifying: "debug": true

Try this mode and make a screenshot with the on-screen debug text.

The popupwindow flag is explained in this image from a reddit thread:
![](https://i.imgur.com/oAeuEB8.png)

**Comment by ryan17** [comment]
Here it is 
![Uploading Arena Helper No Detection.png…]()

**Comment by rembound** [comment]
Thanks for the screenshot. Maybe you need to unblock all of the dlls in the ArenaHelper plugin directory, as well as the dlls in the x86 directory. One way of doing this, is to first unblock the zip-file of the plugin. After unblocking the zip, the dlls inside should be unblocked after unzipping. I hope it works.

**Comment by ryan17** [comment]
I already did that but that didn't work. Anyway i solved the problem i copied and pasted all dlls in the x86 arena helper directory in C:/windows/system32 and C:/windows/SysWOW64. Thanks for the help!

**Comment by Ksoucek** [comment]
Ok  i have already picked my chamion in arena.. so im not able to test if it works now..  but atleast it doesnt stop when i clik on hs

**Comment by HowIsYourMoM** [comment]
When this will be fixed? i need the arena helper now :(

**Comment by HowIsYourMoM** [comment]
OMG Ryan17 thank you so much,what you did works 100%.so brilliant man! you saved my day.

Rembound,nice job,great work on the plugin.You should make a fix to the files to the pple who will download it,so they dont come with this problem and search for a solution.

Thank you both!~

**Comment by rembound** [comment]
The new version includes an updated version of the EMGU library: Emgu.CV-3.0.0-rc1
this should fix the crash issue.
