### ISSUE TITLE
missing MSVCP120.dll and have C++ installed

### ISSUE THREAD

**Issue by AdamAnalytics** [rembound/Arena-Helper#120]
I use HDT and I'm trying to install Arena Helper. I completed steps 1-5, but I don't see any dll files. I installed vcredist_x86.exe, but I got the following message when starting it (see picture). 

I already have Visual Studio 2015 C++ installed on my computer. Could this be causing the issue?

![c issue](https://cloud.githubusercontent.com/assets/20917151/25777262/d167ff10-32a5-11e7-895f-9a75d9bf2ed1.PNG)

Thank you!

Adam

**Comment by rembound** [comment]
Check out issue https://github.com/rembound/Arena-Helper/issues/114

**Comment by AdamAnalytics** [comment]
That explains it. I successfully installed and used arena helper. Thanks!
