### ISSUE TITLE
Can I see cards I did not draft?

### ISSUE THREAD

**Issue by AdamAnalytics** [rembound/Arena-Helper#121]
I want to ask whether I drafted well. For this, I need to know my choices at each stage of the draft. Arena Helper gives the value of each card to choose for drafting, but does it save the cards that I did not pick?

**Comment by rembound** [comment]
The data is saved in the data files. You can see them by opening the deck json files in: `%appdata%\HearthstoneDeckTracker\ArenaHelper\Decks`

**Comment by AdamAnalytics** [comment]
The json files show:
      "Item1": "EX1_044",
      "Item2": "UNG_914",
      "Item3": "OG_254"

How do I know which cards they are?

**Comment by rembound** [comment]
Any card database uses those ids internally. Check out [HearthstoneJSON](https://hearthstonejson.com/)

**Comment by AdamAnalytics** [comment]
How would I use the JSON files to make a reddit post showing all my draft
choices and ask others to evaluate how I did?

**Comment by AdamAnalytics** [comment]
I still don't know how to make a forum post showing my draft decisions in an easy to read format for others. Is there a process to convert the JSON data into a visual display of the draft choices?

**Comment by rembound** [comment]
There is currently no visualization for the data.

**Comment by AdamAnalytics** [comment]
Ok thank you. If you develop this like they have for heartharena, it would be amazing.
