### ISSUE TITLE
Stuck in Getting values since KFT

### ISSUE THREAD

**Issue by fmoraes74** [rembound/Arena-Helper#126]
I started a Rogue arena but on the very first pick it shows it stuck in Getting values...

Let me know of anything that can be done to help fix the issue or investigate it.

**Comment by rembound** [comment]
Check out issue https://github.com/rembound/Arena-Helper/issues/118 for possible solutions.

Quote:
> resetting everything and repointing HDT to Hearthstone's directory

**Comment by fmoraes74** [comment]
This was caused by the HA plugin that was not finding the new cards. It would be nice to have some try/catch around plugins. Anyway, I've disabled it. Closing the issue.
