### ISSUE TITLE
Arena helper stuck on previous pick/detecting arena

### ISSUE THREAD

**Issue by eyal-moscovici** [rembound/Arena-Helper#128]
![capture](https://user-images.githubusercontent.com/31901204/30343586-ac16423c-9806-11e7-8fce-84551364f5cc.PNG)

**Comment by sabertazimi** [comment]
replace 'data' folder manually

**Comment by LeetCodes** [comment]
i have the same issue often, i have had to just stop using the plugin and use heartharena.com web interface for now, every new set of cards it freezes and lags
