### ISSUE TITLE
HDT won't detect plugin after adding Newtonsoft.json to project

### ISSUE THREAD

**Issue by moepmoep12** [rembound/Arena-Helper#129]
Hey,

I'm currently learning C# by creating a plugin for HDT. The plugin worked as intended.
Until i wanted to use a tierlist for ArenaCards which is a .json File.
So i added Newtonsoft.json to my project in order to use the tierlist. 
After building the project and moving the .dll to the plugin folder of HDT, the plugin won't be detected by HDT anymore. 

How do I adjust my plugin properly to be detected by HDT again?

**Comment by moepmoep12** [comment]
oops, wrong repository

**Comment by riQQ** [comment]
As you haven't opened an issue at the HDT repo:
You need to reference the version of Newtonsoft JSON, that HDT itself uses.
