### ISSUE TITLE
TestPlugin not working

### ISSUE THREAD

**Issue by Skillzore** [rembound/Arena-Helper#131]
I am trying to write a plugin for Arena Helper, but I can't even get the test plugin to work at the moment. I add the needed references and build the TestPlugin without errors. I get the TestPlugin.dll from \TestPlugin\bin\Debug and copy it to %APPDATA%\Local\HearthstoneDeckTracker\app-1.5.4\Plugins\ArenaHelper\plugins. But no "p" or comment shows up when running Arena Helper.

Also worth noting, restarting HDT removes the dll file from ArenaHelper\plugins, so it is impossible to restart HDT after adding the dll to ArenaHelper\plugins. Restarting Arena Helper works fine, but does not get the TestPlugin to run. Any ideas?

**Comment by rembound** [comment]
HDT has changed the way plugins are loaded. There are now two plugin directories that are somewhat synced. Try adding to both directories. One is in the install dir and the other is in %appdata%
