### ISSUE TITLE
Significant lag during draft

### ISSUE THREAD

**Issue by rusticdog** [rembound/Arena-Helper#135]
I had to uninstall HDT and rename off C:\Users\[username]\AppData\Roaming\HearthstoneDeckTracker then reinstall to get Arena Helper back up to snappy speed.  That obviously means losing all data, but not important.

I tried first reinstalling HDT and the plugin, but neither resulted in an improvement.   I've attached the HDT log that seems to display these delays.

I do still have a copy of the old data folder if anything in that might be useful.  I've seen a few folk complain about performance.

[hdt_log.txt](https://github.com/rembound/Arena-Helper/files/1797014/hdt_log.txt)

**Comment by rembound** [comment]
I have also noticed the lag. The lag is caused by HDT, so I can't do much about it.
The plugin has to wait until HDT has updated the data, maybe something changed.

**Comment by rusticdog** [comment]
OK thanks, will follow up with HDT

**Comment by rembound** [comment]
Fixed with v0.9.0, see: #137
