### ISSUE TITLE
Arena Helper freezes during pick

### ISSUE THREAD

**Issue by redminstrel** [rembound/Arena-Helper#137]
Almost every time I try to use this, Arena Helper Freezes.  I cannot even select options or anything.  It detected the heros, but did not detect my choice.  It detected my first set of cards, but not what I chose, and now still shows those first three cards.

**Comment by Moldavone** [comment]
I have the same problem after the update.

**Comment by peroxidex** [comment]
Not sure what's causing it, but the previous release seems fine if you want to rollback to it and simply not update.

**Comment by chaosjockey** [comment]
I've enabled debug in the plugin but it will only do one of two things freeze up and not detect anything or the previously detected cards remain displayed.

I've tried enabling manual card picking but that isn't working either, tried enabling interactivity from within HDT too just to be sure.

Could it be having permission problems reading the hearthstone log? Something getting stuck in memory?

**Comment by rembound** [comment]
Thanks for your reports, I didn't notice that the gui itself was freezing before.
I have fixed the freezes in v0.9.0, it should be a lot faster now.
