### ISSUE TITLE
Plugin Shows Ratings of "Previous Screen"

### ISSUE THREAD

**Issue by XenoXilus** [rembound/Arena-Helper#138]
At the start of my draft, it detects and shows the 3 heroes just fine.

I pick a hero, and the plugin shows the 3 heroes, and overlays N/A below the 3 offered cards.
I pick a card. The plugin now shows the first 3 cards that were offered, and the overlay now shows the 3 ratings for the 3 first cards offered.

**Comment by grobson13** [comment]
Same issue here.

**Comment by rembound** [comment]
Fixed with v0.9.1.
Thanks for your reports!
