### ISSUE TITLE
Helper loses window focus during Hero Selection 

### ISSUE THREAD

**Issue by VeXHarbinger** [rembound/Arena-Helper#14]
First off, great job.  I really like this utility.  I find it interesting and helpful at least it was before the last day or so.   Now after it detects the possible hero, when you select one the Helper window displays the lost window focus/detecting message.  This is when the Choose option is displayed for the hero, because of the lost focus the selected hero does not become large in the helper box.   I had just read about how to turn on debugging, so I went and was able to just enter the selected hero type in the related arena json file and, the rest of the draft worked as expected.  I assume this error was introduced with the new heroes patch of HS.  I'm sure the change and solution will be pretty evident for you.

I hope you at least have a sandbox to test in, or do you actually have to buy a run to test?

**Comment by rembound** [comment]
This should be fixed in the new version. The Hearthstone patch changed some of the graphics and the visual hashes I use have changed.

I can test a bit on screenshots, but for best testing, I use actual arena runs.
