### ISSUE TITLE
Card value shown as n/a

### ISSUE THREAD

**Issue by equisdero** [rembound/Arena-Helper#141]
Tried the plug-in with current version (9.1). Instead of showing the value of cards, it shows n/a for everyone, and when picking a card it would not register. Hearthstone Deck Tracker gave me the error code below:
> Make sure you are using the latest version of the Plugin and HDT.
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ArenaHelper.Plugin.<CheckDataUpdate>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ArenaHelper.Plugin.<CheckUpdate>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rembound** [comment]
Make sure you have installed the plugin correctly by following: https://github.com/rembound/Arena-Helper#how-to-install

You could also try clearing the `%AppData%/HearthstoneDeckTracker/ArenaHelper/Data` directory.
Otherwise, maybe there is an installation problem with HDT itself.

I just tried the plugin myself and it is working without problems.

**Comment by equisdero** [comment]
I forgot to unblock the zip file, oops.
