### ISSUE TITLE
Lightforge tier list updated for Taverns of Time event

### ISSUE THREAD

**Issue by marlonrichert** [rembound/Arena-Helper#143]
Taverns of Time started today: https://playhearthstone.com/en-us/blog/21816202

Lightforge tier list updated today, too: http://thelightforge.com/TierList/ChangeLog

https://github.com/rembound/Arena-Helper/blob/master/data/cardtier.json needs to be updated with the new Lightforge scores.

**Comment by KainMorgen** [comment]
Afaik Rembound stopped working on the arena helper. :(

**Comment by rembound** [comment]
I'm keeping it updated, thanks for waiting a bit!
