### ISSUE TITLE
Weaponized Piñata missing tier score value

### ISSUE THREAD

**Issue by thoughthouse** [rembound/Arena-Helper#144]
![pinata](https://user-images.githubusercontent.com/7727575/44129329-f0e471c0-a004-11e8-83be-25e9d1414ccd.PNG)

**Comment by rembound** [comment]
Thanks for the report!
Updated the tierlist with the fix.

The Lightforge tierlist uses the id `BDP_025` for the card, but it should be `BOT_401`.
