### ISSUE TITLE
Lightforge tier list has been updated AGAIN on 2018-08-24

### ISSUE THREAD

**Issue by marlonrichert** [rembound/Arena-Helper#146]
Yep, only 2 days after the last update. 😕 See http://thelightforge.com/TierList/ChangeLog

https://github.com/rembound/Arena-Helper/blob/master/data/cardtier.json needs to be updated yet again.

**Comment by marlonrichert** [comment]
@rembound Could you update again, please? 🙂 Your values are not yet in sync with The Lightforge's. See here for examples of the biggest differences: http://thelightforge.com/TierList/ChangeLog

**Comment by rembound** [comment]
I always update the list, but sometimes there is a small delay. Thanks!
