### ISSUE TITLE
Dual Class Arena glitch

### ISSUE THREAD

**Issue by KainMorgen** [rembound/Arena-Helper#149]
When choosing the hero power for the dual class arena that hero power is added as a card to your deck (twice, even) and thus the draft recognizes your first pick as card 3/30.
The last two drafts don't get their rating shown as the Arena Helper thinks the deck is already full. So you have to edit them into the decklist manually after deleting the two hero power cards.

**Comment by rembound** [comment]
Thanks for the report!
Should be fixed with Arena Helper v0.9.2.
