### ISSUE TITLE
Golden Heroes and New Heroes not detected yet

### ISSUE THREAD

**Issue by rembound** [rembound/Arena-Helper#15]
**Update:**
Here is an updated overview of the supported portraits and the portraits I still need:

Should be supported:
New heroes: Magni, Alleria, Medivh
Golden portraits: Warrior, Hunter, Mage

Supported in next update:
Golden portraits: -

Still needed:
Golden portraits: Druid, Shaman, Paladin, Warlock, Mage, Priest

**Original post:**
I don't have the visual hashes for the golden heroes and the new heroes yet, so the plugin can't detect them. If you have any of the heroes, you can help out by taking some screenshots as described below. In the meantime, you can use the manual hero selection override of versions 0.3.0 and above by clicking on the top-left portrait rectangle and selecting your hero.

1) Set your resolution to 1280x960, in window mode.
2) Take screenshots with Print-Screen, the files will appear on your desktop. The screenshots should be in the lossless .png format.
3) Make sure the resulting png is exactly 1280x960 pixels.
4) Reply to this thread and upload your screenshots by dragging them in the reply window.

I will need screenshots of the following scenes:
Heroes:
![hearthstone screenshot 05-31-15 13 38 16](https://cloud.githubusercontent.com/assets/11648276/8183975/f09a4562-143b-11e5-91ab-570db8bc5e7d.png)

Selected Hero:
![hearthstone screenshot 05-31-15 13 49 55](https://cloud.githubusercontent.com/assets/11648276/8183982/f7ca9bac-143b-11e5-8bed-da2618d76b32.png)

Thank you for your help!

**Comment by et1a1nen** [comment]
Hello! Here is Warrior.
![hearthstone screenshot 06-24-15 20 42 34](https://cloud.githubusercontent.com/assets/4366899/8337106/a1611f30-1ab1-11e5-92ea-4e994018dca2.png)
![hearthstone screenshot 06-24-15 20 42 41](https://cloud.githubusercontent.com/assets/4366899/8337107/a1623eec-1ab1-11e5-9b90-10ed1c1d6380.png)

**Comment by rembound** [comment]
Thanks. Will add the hashes in the next release.
Hopefully it works with the animations though.

**Comment by SOLiNARY** [comment]
![hearthstone screenshot 06-30-15 18 52 55](https://cloud.githubusercontent.com/assets/3579801/8432373/ba0e6c10-1f50-11e5-9ad5-276e767c1e92.png)
![hearthstone screenshot 06-30-15 18 52 48](https://cloud.githubusercontent.com/assets/3579801/8432374/ba2b84c6-1f50-11e5-87dd-6f2ecee01664.png)

**Comment by rembound** [comment]
Thank you. Added the hashes to the repo, will be in next release.

**Comment by TheGoblinHero** [comment]
Alleria
![hearthstone screenshot 07-02-15 13 48 20](https://cloud.githubusercontent.com/assets/12325495/8475549/7d4619fa-20c1-11e5-885f-6aab08609803.png)
![hearthstone screenshot 07-02-15 13 47 54](https://cloud.githubusercontent.com/assets/12325495/8475550/7d783c14-20c1-11e5-8036-783e5fde53c3.png)

**Comment by rembound** [comment]
Thanks, added the hashes.

**Comment by SuperGouge** [comment]
Here is golden Valeera:
![hearthstone screenshot 07-02-15 19 36 52](https://cloud.githubusercontent.com/assets/3006175/8483707/d8000a00-20f2-11e5-9684-0115ed50fddf.png)
![hearthstone screenshot 07-02-15 19 36 57](https://cloud.githubusercontent.com/assets/3006175/8483712/dbfd43ca-20f2-11e5-8e33-859e68038112.png)

**Comment by dchristian3188** [comment]
Golden Warrior and Hunter
![hearthstone screenshot 08-10-15 17 39 33](https://cloud.githubusercontent.com/assets/13060023/9187544/d6a9ec54-3f86-11e5-8abc-2b06ad730a10.png)
![hearthstone screenshot 08-10-15 17 39 28](https://cloud.githubusercontent.com/assets/13060023/9187545/d6aaf57c-3f86-11e5-9748-4c20cd3ec230.png)
![hearthstone screenshot 08-10-15 17 39 20](https://cloud.githubusercontent.com/assets/13060023/9187546/d6ab4144-3f86-11e5-8ed8-837ff057819d.png)

**Comment by rembound** [comment]
Thanks! When TGT is released and supported by Hearthstone Deck Tracker, I will update the program and add this.

**Comment by dchristian3188** [comment]
Golden Druid
![hearthstone screenshot 08-27-15 16 15 22](https://cloud.githubusercontent.com/assets/13060023/9535498/de7d5c9c-4cd6-11e5-9377-7d92af5f7bee.png)
![hearthstone screenshot 08-27-15 16 15 16](https://cloud.githubusercontent.com/assets/13060023/9535499/de987b08-4cd6-11e5-8134-5bd37f1a0185.png)

**Comment by rembound** [comment]
Thanks! Will add it in the next update.

**Comment by rembound** [comment]
@dchristian3188 After downloading the images, I see that they have a resolution of 1260x900, while I need images of 1280x960. The process is almost pixel perfect, so I can't just scale the images.

**Comment by wittenbe** [comment]
I suggest you actually use hearthhead for this, e.g. http://www.hearthhead.com/hero=4/uther-lightbringer
The images are always framed the same way.
For golden heroes, phash every frame of the gif. (hearthhead doesn't have every frame of the animation, but it's better than nothing). To reduce the match search space a bit, check each frame's phash against all others. If they're the same, don't save duplicates to your db.

**Comment by rembound** [comment]
Thanks for the suggestion. The small golden portraits could be usable, if I do some scale conversions. They don't have the big portraits, so that could be a problem.

**Comment by wittenbe** [comment]
Why would that be a problem if you're using phashes? You scaling the images down anyway for the DCT.

**Comment by rembound** [comment]
I added the big portraits as an extra check. If the images are of high enough quality, they might not be needed. Will have to test it.

**Comment by riQQ** [comment]
![](https://cloud.githubusercontent.com/assets/3404787/14410116/c385386c-ff26-11e5-97ee-858e8f988c92.png)
![](https://cloud.githubusercontent.com/assets/3404787/14410117/c3a2792c-ff26-11e5-94aa-d00a016bdd99.png)

**Comment by YarMur** [comment]
Khadgar portrait isn't detected. Please add it hashes.
![hearthstone screenshot 05-05-16 07 59 31](https://cloud.githubusercontent.com/assets/19200184/15036463/e911acb2-1297-11e6-821d-d6851e34b5fe.png)
![hearthstone screenshot 05-05-16 07 59 37](https://cloud.githubusercontent.com/assets/19200184/15036470/f6346a74-1297-11e6-9749-d919780790e4.png)

**Comment by rembound** [comment]
Will be in the next version, thanks!

**Comment by Slikkster** [comment]
Hi Rembound,

Thanks for the plugin, I prefer it to Overwolf. I humbly request the addition of Morgl the Oracle :)
![hearthstone screenshot 08-12-16 20 42 37](https://cloud.githubusercontent.com/assets/13022736/17641285/9835bd54-60cd-11e6-8b21-dad7d02cb24f.png)
![hearthstone screenshot 08-12-16 20 42 18](https://cloud.githubusercontent.com/assets/13022736/17641284/983461f2-60cd-11e6-8b1f-a599a6209ba1.png)

Thanks!

**Comment by rembound** [comment]
Thanks for the images! Will be in next update.

**Comment by riQQ** [comment]
![2017-11-12 21_20_35-hearthstone](https://user-images.githubusercontent.com/3404787/32702972-6507b740-c7ef-11e7-9325-297550d1c553.png)

**Comment by rembound** [comment]
Thanks, but the plugin doesn't use visual hashes anymore to detect cards and heroes. It uses the log and memory-reading functions from HDT. So it should always work, even when there are updates.

**Comment by riQQ** [comment]
Mmh strange, if i remember correctly it didn't work.
