### ISSUE TITLE
Not detecting heroes

### ISSUE THREAD

**Issue by niccorihayachan** [rembound/Arena-Helper#153]
Hi,
not detecting heroes,can you help me?
![Hearthstone Screenshot 04-28-19 04 13 30](https://user-images.githubusercontent.com/50057287/56854131-b70d5700-696c-11e9-8863-3af3d97107fe.png)

**Comment by niccorihayachan** [comment]
sorry this picture is correct
![タイトルなし](https://user-images.githubusercontent.com/50057287/56854143-03f12d80-696d-11e9-8268-16f62d334534.png)

**Comment by rembound** [comment]
Looking at the images, you already have selected a Hero. You should start Arena Helper before choosing a hero.

You can fix it manually by clicking on the gray square in the top-left corner and selecting the correct hero.
