### ISSUE TITLE
Arena Helper Window not visible

### ISSUE THREAD

**Issue by Azlodin** [rembound/Arena-Helper#16]
The Arena helper window is no longer displaying within the Hearthstone window. The plugin is running but it is not visible on screen. I cannot locate how to reset the window (if the position is somehow off screen) or make it re-appear

**Comment by corlettb** [comment]
Try opening up:
C:\Users<username>\AppData\Roaming\HearthstoneDeckTracker\ArenaHelper\arenahelper.json

and zero the position values. Or delete the file entirely.

**Comment by Azlodin** [comment]
Thanks, that did the trick!

**Comment by rembound** [comment]
Fixed with the latest release.
