### ISSUE TITLE
Next HDT release will update several dependencies

### ISSUE THREAD

**Issue by azeier** [rembound/Arena-Helper#162]
Hey,

I just wanted to let you know that the next HDT release will update several dependencies (see https://github.com/HearthSim/Hearthstone-Deck-Tracker/compare/11e1df49c160...6bb404dedc50) and upgrade [HearthDb](https://github.com/HearthSim/HearthDb) to .NET Standard 2.0.

This means the current release of Arena-Helper will no longer load. You will likely need to upgrade to at least .NET Framework 4.6.1 if you interact with HearthDb in any way.

The next version will likely be released on April 27th or 28th. I apologize for the short notice.

You can find a dev build for the new release [here](https://github.com/HearthSim/HDT-dev-builds/releases/latest) or on the [master branch of HDT](https://github.com/HearthSim/Hearthstone-Deck-Tracker).

**Comment by rembound** [comment]
Just updated. Thanks for letting me know!
