### ISSUE TITLE
Arena Helper no longer appearing in Plugin list since HDT 1.11

### ISSUE THREAD

**Issue by nathanmchoi** [rembound/Arena-Helper#164]
Hi,
After the update to HDT to 1.11.0, some of my plugins disappeared from the plugin list. Three of them 
(Shamanic, Trouble at the Mill, and Graveyard) were unaffected, but Pack Tracker and Arena Helper both disappeared from the list, although their files were unchanged. An update was released from Pack Tracker that fixed the issue, but Arena Helper still doesn't work.

BTW thanks so much for making this! I had never gone above 4 wins in arena before because it was always such a pain to look up the tier list for every draft, but my first run with the helper and I went all the way to 10 wins! (Almost 11 but my opponents imprisoned felmaw ignored my 4 minions and went face for lethal the turn before I had lethal).

**Comment by chWolfgang** [comment]
I can confirm this.  Also, thanks as well.

**Comment by rembound** [comment]
I've updated for the new changes and Arena Helper v0.9.4 is now available.
Great to hear about your success. Thanks!
