### ISSUE TITLE
Bullsh*t

### ISSUE THREAD

**Issue by HelloIsDomo** [rembound/Arena-Helper#169]
Do you really think that maiev has more value than mind reader? Or like holy smite? For everyone that can read my message DO NOT download this "helper" you would probably lose 150 gold, and for f2p players 150 gold are missing cards and dust, I repeat, DO NOT download this plugin.

**Comment by chWolfgang** [comment]
Who are you? What expertise do you have in Arena? Why are your numbers/games better thank the many this plugin uses? Some context would be useful. Links? Replays? Blogs? Awards? VoDs? Anything?

No? Okay, so you are just a child throwing a tantrum. Sorry you are having a bad day. Go have some cool-aid and get a hug from mom.

**Comment by swilkins1337** [comment]
The numbers come from [here](http://thelightforge.com/TierList), so take it up with them. Have a better attitude if you do.
