### ISSUE TITLE
Incorrect card highlighted

### ISSUE THREAD

**Issue by corlettb** [rembound/Arena-Helper#18]
I've noticed several times that the wrong card is highlighted when the card comes out as a whole number and the others are doubles.

See below for example.

![screen shot 2015-06-24 at 21 16 52](https://cloud.githubusercontent.com/assets/2338074/8340613/8cfef20a-1ab7-11e5-953e-9c0c9c23d51b.png)

At a glance this might have to do with the regex in the below where "." might need to be escaped.

        public double GetNumericalValue(string str)
        {
            // Strip everything except numbers and dots
            var nstr = Regex.Replace(str, "[^0-9.]", "");
            double dvalue = 0;
            try
            {
                dvalue = System.Xml.XmlConvert.ToDouble(nstr);
            }
            catch (Exception)
            {
            }

            return dvalue;
        }

**Comment by rembound** [comment]
What happens is, every character except the allowed characters are stripped. The resulting numbers are: 76.768, 70.3458 and 1720

What I could do is, only take the part before a space and ignore the rest.

**Comment by rembound** [comment]
Added support with the latest release.
