### ISSUE TITLE
Detects heroes, but stops working after I select one.

### ISSUE THREAD

**Issue by ultrababa** [rembound/Arena-Helper#19]
It detects the 3 heroes but after I select one of the three, it shows it for a split second, and then goes back to the 'detecting arena' state. Issue started happening just yesterday. It was working fine for a month or so. Thanks in advance.

**Comment by rembound** [comment]
Have you upgraded to the latest version v0.3.0 ?
The new Hearthstone patch introduced some graphical tweaks, so the plugin needed some updates.

In the new release, there is also a manual hero selection override. Click the top-left rectangle to select your hero, if detection doesn't work.

**Comment by ultrababa** [comment]
Ok, I feel really stupid now. I was always checking for any HDT updates, but not for Arena Helper.
Problem solved. Thanks for answering and for this great addon.
