### ISSUE TITLE
Heroes not being detected

### ISSUE THREAD

**Issue by Elitesparkle** [rembound/Arena-Helper#2]
I'm trying the plugin.

Every time I starts it, it stops at "Detecting heroes...".
The Hearthstone windows has the focus and nothing overlaps the key elements.

**Comment by rembound** [comment]
It could be that the Hearthstone window is too small to properly detect the Heroes. Try resizing or maximizing the window. If it doesn't work, take a screenshot and post it.

**Comment by Elitesparkle** [comment]
I've done multiple attemps, before and after opening the issue.

After restarting Hearthstone, it worked somehow.
I've tried two times to be sure. It works.

Maybe I had to restart everything before trying to use it.
Can you confirm/deny for sure?

**Comment by rembound** [comment]
If it displays "Detecting heroes...", it means it has already successfully detected the Arena. This means that the screen is captured correctly and at least one visual element was detected. The plugin recognizes a hero when it is detected multiple times in a row. This could take one or two seconds. During this time, you shouldn't hover the heroes with the mouse, or overlap them. Restarting shouldn't matter.

**Comment by n4ru** [comment]
I'm actually having this issue on my desktop, but not on my laptop. My desktop has two displays.

**Comment by rembound** [comment]
You can enable some on-screen debug information by going to the AppData directory: HearthstoneDeckTracker\ArenaHelper\ opening arenahelper.json and modifying: "debug": true
Maybe if you take a screenshot I can see what is going on.

**Comment by n4ru** [comment]
I had -popupwindow flags enabled in Hearthstone. Taking this off solved this issue for me. What's odd is the configuration is the same for me on my Laptop, and I had no issues with that flag on.

**Comment by SafoGamer** [comment]
I'm having the same issue. It all started the day the Brawler patch went live. I don't have any flags enabled in Hearthstone. I tried different resolutions with and without full screen. I just deleted the 0.3.0 and tried the new 0.4.1 to see if it solved and it still wont detect the Heroes. 
Here is a screenshot of the debug mode:

![hearthstone screenshot 07-06-15 16 26 04](https://cloud.githubusercontent.com/assets/13206835/8531195/05b2cc42-23fc-11e5-990b-6c33b08ba6e4.png)

**Comment by rembound** [comment]
@SafoGamer See my answer to #4

**Comment by Eon-Drache** [comment]
I'm following the steps to a t and have tried multiple different things. Read the other thread and can't get the tracker to work at all. It won't detect the hero or cards chosen.

**Comment by Ksoucek** [comment]
https://www.youtube.com/watch?v=BqXclnhFRVI can you help me ?

**Comment by rembound** [comment]
I don't know if I can help, other than stating my previous answer below. The dll can't be found, so the dlls in "Hearthstone Deck Tracker\Plugins\ArenaHelper\x86" are not found or are blocked. You could try to remove the entire ArenaHelper directory and re-install the plugin by using the installation instructions.

Quote:
>This is an installation problem. The correct dlls are not found. Please see the "How to Install" section of the readme.

>As a final step, the readme suggests:

>>    8) If all else fails, copy the dlls from the x86 directory to the C:/windows/SysWOW64 directory.

>Step 8) shouldn't be necessary if you have followed all of the installation steps.

**Comment by Ksoucek** [comment]
im sorry....my bad.... i copied x86 as a FOLDER... so it does not work... after i copy only dlls it starts working

**Comment by rembound** [comment]
No problem! I'm glad it works now.

**Comment by Eon-Drache** [comment]
Can we get like a Screenshot of what the plugin folder should look like if installed correctly?

**Comment by riQQ** [comment]
Here you go:
![plugin folder](https://cloud.githubusercontent.com/assets/3404787/9972425/95d64e32-5e64-11e5-8503-099afcadfc7b.png)

**Comment by Elitesparkle** [comment]
@rembound, can you add the possibility to manually choose an Hero from the whole pool of nine Heroes?

**Comment by rembound** [comment]
@Elitesparkle This feature already exists! Click the top-left portrait to select a hero.

**Comment by Elitesparkle** [comment]
Oh, I didn't notice it or read about it.

In this case, I suggest to add a tip when you start a new Arena run, just
below the detecting Arena warning.
Il 20/set/2015 12:59, "Rembound" <notifications@github.com> ha scritto:

**Comment by rembound** [comment]
When the plugin is detecting the heroes, there is already a tip at the bottom of the screen. This message is only visible when the heroes are still being detected, so it is possible that you didn't see it.
