### ISSUE TITLE
Invisible window

### ISSUE THREAD

**Issue by Thristle** [rembound/Arena-Helper#23]
using the latest AH with HDT and the plugin window is always invisible.
tried reinstalling HDT and AH. and other plugins works fine (collection tracket)

**Comment by ekohilas** [comment]
I also had this issue
unfortunately I don't remember how I fixed it.

**Comment by rembound** [comment]
If you activate the window from the HDT menu again, while it is already open, the window position will reset. Will fix it for the next version.

**Comment by Thristle** [comment]
can't believe i didn't try that. worked like a charm

**Comment by Thristle** [comment]
can't believe i didn't try that. worked like a charm

**Comment by rembound** [comment]
Version updated.
