### ISSUE TITLE
Error with opencv_core300.dll not beeing found

### ISSUE THREAD

**Issue by Vash115** [rembound/Arena-Helper#26]
I did all you said, even copiad all the .dll's to SysWOW64 , still, it doesnt work. any ideas?

**Comment by rembound** [comment]
If the dll is in the right place and unblocked, I have no idea what could be the problem. Maybe something external, like a virusscanner or something?

**Comment by Vash115** [comment]
I just restarted hdt and it worked :P thanks for the answer tho.
