### ISSUE TITLE
plugin doest track

### ISSUE THREAD

**Issue by hatyak** [rembound/Arena-Helper#27]
Hello there,
my plugin has stopped working since the latest patch. doesn't detect heroes or cards, even if i manually pick a hero. If i turn on debug mode nothing happens at all, expect 3 lines of text:
""""""""""""""""""""""""""""""""""
-Arenacheck1: 30
-Arenacheck1: 40

Elapsed: "xx"
""""""""""""""""""""""""""""""""""
I have installed it severeal times, unblocked zips, copied dll-s to both syswow64 and sys32 dirs, i even reinstalled deck tracker, removed files from appdata, try every possible resolution combination,  full screen running 
![a_helper_stucked](https://cloud.githubusercontent.com/assets/13683783/9418643/428c90f6-484d-11e5-81be-1478758513dd.jpg)
and -popupwindow setting.its still not working.

Looking forward to your reply
Thanks

**Comment by hatyak** [comment]
after a restart it has started to work again, still dont know what was the problem. i close this thread tho.

**Comment by rembound** [comment]
I'm glad it works again. In the picture I see that the arena was not detected, visually. So the plugin worked, but something on the screen was not right. The problem could be the resolution or the aspect ratio.
