### ISSUE TITLE
Next HDT Update

### ISSUE THREAD

**Issue by Epix37** [rembound/Arena-Helper#28]
The next HDT update will most likely require some (minor) changes for your plugin to properly work.

See here for more info and a pre-release download: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.12PRE3

**Comment by rembound** [comment]
Thanks for the notice. The plugin still works with the pre-release, but I will keep an eye out for incompatible changes.

**Comment by Epix37** [comment]
Just looking at your Plugin.cs, [this](https://github.com/rembound/Arena-Helper/blob/master/Plugin.cs#L979) will no longer work properly, as `Game.cs` will no longer be used. 

(Turns out you can't actually access the GameV2 instance at the moment, I'll add that to the API.)

**Comment by Epix37** [comment]
You can now get the latest pre-release here: https://github.com/Epix37/HDT-Test/releases

**Comment by Epix37** [comment]
If I find no more major problems the update should go out [11am UTC](http://everytimezone.com/#2015-8-24,-60,cn3).

**Comment by rembound** [comment]
Thanks, updated the repo. Will release after HDT.
