### ISSUE TITLE
Some new TGT cards aren't being properly detected

### ISSUE THREAD

**Issue by MistoFox** [rembound/Arena-Helper#29]
More specifically the Spawn of Shadows card (priest's new class card, 4 mana, minion), the plugin was having trouble reading it, kept detecting it as it was a Imp Master and auto increment the card count a bunch of times even tough I wasn't clicking anything.

**Comment by rembound** [comment]
The two cards look visually similar, if you look at the shapes. If your resolution is low, this problem is more likely to happen.

I just drafted a deck including the new cards, and they were all detected properly. If it happens again, you could enable the debug mode and take a screenshot.
