### ISSUE TITLE
values in incorect place

### ISSUE THREAD

**Issue by koalafishy** [rembound/Arena-Helper#31]
Hi,
not really a big issue but the values dont line up underneath each card. I'm running the game at 1920x1080 fullscreen below but they are in exactly the same location when windowed or running at any other resolution
thanks, otherwise an awesome plugin

![image](https://cloud.githubusercontent.com/assets/13992304/9828320/4f212146-58b1-11e5-833d-37ca1cb880af.png)

**Comment by rembound** [comment]
I can't replicate this issue. Try manually resizing the window or restarting everything. The plugin should automatically adjust to the screen size.

**Comment by koalafishy** [comment]
I have tried re-sizing the window and restarting both didn't help.
Sadly i am crap and don't have the gold to start another run and fiddle anymore, I will look again when I saved up tomorrow
