### ISSUE TITLE
Automatically sync with https://www.heartharena.com/

### ISSUE THREAD

**Issue by JesseBilsten** [rembound/Arena-Helper#34]
Would it be possible to save the deck/draft to the website after it's done? This would display synergies and other benefits from the site. Additionally showing those in the overlay would help card picks.

**Comment by rembound** [comment]
I would refer to the HDTAHPluginHAPlugin plugin by corlettb that can be found in the readme.

**Comment by JesseBilsten** [comment]
Thanks! I apologize, I must have missed that in the README initially.

**Comment by JesseBilsten** [comment]
After installing and using the plugin,it does not do what I was asking. It does show the updated values and pulls information from the website during the draft, but it does not export or save the drafted deck to the website for tracking.

Is this possible?

**Comment by rembound** [comment]
You could suggest it to the developer or fork it, but the development hasn't been very active. I can't really support it myself.
