### ISSUE TITLE
Missing ArenaHelper.dll file??

### ISSUE THREAD

**Issue by kyguymd** [rembound/Arena-Helper#35]
>Download the ZIP

>Unblock ZIP

>Extract ZIP

>There is no ArenaHelper.dll file.....

I am assuming this is the reason the ArenaHelper is not showing up on DeckTracker

**Comment by kyguymd** [comment]
This is my folder... http://puu.sh/ktQKL/3cd9fd4f92.png

**Comment by riQQ** [comment]
You downloaded the source code instead of the binaries.

**Comment by kyguymd** [comment]
thanks dude!
