### ISSUE TITLE
Issues with DPI

### ISSUE THREAD

**Issue by Xilef11** [rembound/Arena-Helper#37]
I changed the DPI settings of my computer to make things bigger, and the card values are not aligned with the cards.
this was solved in HDT, (see https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/808 ), but Arena Helper still has the issue

**Comment by rembound** [comment]
Hopefully fixed in next version.

**Comment by Xilef11** [comment]
fix confirmed. thanks
