### ISSUE TITLE
Not detecting arena since 0.5.5

### ISSUE THREAD

**Issue by myxiplx** [rembound/Arena-Helper#39]
Hi,

Ever since HDT was updated requiring 0.5.5 of Arena Helper I haven't been able to get this to work, it won't detect the heros in arena at all.

I've followed all the installation instructions carefully, unblocking the zip file, removing the old version, even copying the DLL's into the appropriate windows folder.  Nothing so far has made any difference.

Do you have any suggestions, or are there any diagnostic logs I can post up here?

**Comment by rembound** [comment]
You could enable the debug mode in the options to see some additional info.
If only the heroes aren't detected, you can manually select a hero using the top-left portrait rectangle.

**Comment by myxiplx** [comment]
Nope, it doesn't detect arena at all.  I've just re-installed HDT and Arena Helper, with both going into a new folder and still have the same problem.

![arena helper not working](https://cloud.githubusercontent.com/assets/15339877/10907978/1ebb4420-8226-11e5-9515-0d1b44e77fff.png)

**Comment by myxiplx** [comment]
I've also just tried totally removing the HDT content from the appdata folder and trying again with default settings for both programs, but get the same effect.

**Comment by myxiplx** [comment]
Well, go figure.  I rebooted my computer after the clean install and it's working fine.  And then I shutdown and put my old settings back in the appdata folder, and now it's still working and I have all my decks and stats back too.

Something must have gotten stuck, and I use hibernate a lot so I probably hadn't rebooted in a month or two.

**Comment by rembound** [comment]
I'm glad it works!

The debug info tells me that the the plugin was correctly installed, but the visual hashes couldn't be detected. Arenacheck1 should be below 10, while it is at 34. Maybe the screen couldn't be captured in a correct way or something else.

**Comment by myxiplx** [comment]
Hmm, it's started doing it again.

I'm travelling with work, so I've gone from my normal home setup of dual external screens, to having a single laptop screen.  So my desktop has changed resolution and layout completely (and I'm running Windows 8 so I think screen scaling changes too).

The Arena Helper window was also totally off the screen and I had to manually move it back on.

I'm pretty sure a reboot will get it working again, but if there are any logs you'd like me to collect in the meantime just let me know.

**Comment by Tolkerism** [comment]
I just started using the arenahelper and its values for arenachecker1:32 and arenachecker2:26 aside from that it just stay stuck like myxiplx's. Rebooting seems to  do nothing for me, and also i dont know if having HDT's overlay affects but i've hidden it to no change

**Comment by rembound** [comment]
The aspect ratio of the window could be messing with the detection. The plugin doesn't support all aspect ratios. Try to set the window to a 1920x1080 or similar resolution.

Rebooting the system might be resetting the window size, hence why it would work.

**Comment by Tolkerism** [comment]
Alright, i'll post results when i cab

**Comment by myxiplx** [comment]
I just tried dragging the hearthstone window over to my second monitor before starting arena helper and that got it working again.  So yeah, it seems screen resolution or the window settings are having an effect.
