### ISSUE TITLE
Not moving on from Detecting Arena 

### ISSUE THREAD

**Issue by supersigi** [rembound/Arena-Helper#4]
I have tried everything, restarted the tracker and Hs, used window and fullscreen mode, still when i start a new run, it stucks at the Detecting arena.. state. What can i do about it ?

**Comment by rembound** [comment]
It should work on most resolutions, but the reference resolution is 1280x960. Set your window to this resolution in the options menu, to try it out. The plugin tries to detect the top of the screen that has the text "The Arena". Maybe the plugin does not work correctly when using a different locale, a language other than English. If you could take one or more screenshots using the 1280x960 resolution in png and upload it, I could analyze the problem.

**Comment by supersigi** [comment]
![hs](https://cloud.githubusercontent.com/assets/12770049/8019352/40e0f826-0c4a-11e5-99cb-374b9072eea8.png)
Desktop res Full hd , Game res. 1280x960

**Comment by rembound** [comment]
I don't see the window borders. Do you use some kind of borderless-window tool?

**Comment by Epix37** [comment]
The problem (at least with this screenshot) is that hearthstone is not in foreground, in which case Helper.CaptureHearthstone will return null.

With 0.10.2 (I think) I added `bool requireInForeground = true` as a default parameter, you might want to set that to false.

Assuming this is the case, detection should work as soon as you focus the hearthstone window.

**Comment by supersigi** [comment]
Its just because the Screen Capture Program what i used, look like this. Normally the game is on fullscreen, and the active window, still not working the detection. Tried to spam the New Arena button.

**Comment by rembound** [comment]
The new release will now capture the screen, even if unfocused. Maybe this will help.

If you go to the AppData directory: HearthstoneDeckTracker\ArenaHelper and find the arenahelper.json file, you could enable a debug option, by setting:
"debug": true

When this option is enabled, you can see some more information in the top-left of the screen.

**Comment by corlettb** [comment]
I've seen this once before and had to click the 'new arena' button to kick start the detection.

**Comment by hoopaholic87** [comment]
I'm having the same issue. I tried your advice with the resolution. Made sure HS was in foreground, still unresponsive. Spammed "new arena" a few times...nothin.

**Comment by corlettb** [comment]
In the same dir that config file is... The one with that .json file for setting the position. There is a sub-dir with all your arena runs in there. Try moving those files out somewhere and restarting. Just wondering if the latest one is corrupt somehow. If that does fix it. Post the latest file :)

**Comment by rembound** [comment]
When you click on New Arena, it is a clean uncorrupt one.

In another thread, someone said that using the "-popupwindow" flag in the Hearthstone options might interfere with the detection. If you use this flag, try to remove it.

**Comment by SafoGamer** [comment]
I'm having the same issue. It all started the day the Brawler patch went live. I don't have any flags enabled in Hearthstone. I tried different resolutions with and without full screen. I just deleted the 0.3.0 and tried the new 0.4.1 to see if it solved and it still wont detect the Heroes. 
Here is a screenshot of the debug mode:

![hearthstone screenshot 07-06-15 16 26 04](https://cloud.githubusercontent.com/assets/13206835/8531231/47060524-23fc-11e5-86f8-6d842f0fcbbd.png)

**Comment by rembound** [comment]
This is an installation problem. The correct dlls are not found. Please see the "How to Install" section of the readme.

As a final step, the readme suggests:
>8) If all else fails, copy the dlls from the x86 directory to the C:/windows/SysWOW64 directory.

Step 8) shouldn't be necessary if you have followed all of the installation steps.
