### ISSUE TITLE
Detection engine seems much slower after update...

### ISSUE THREAD

**Issue by WaxPaper** [rembound/Arena-Helper#40]
It was either the last update or the one before it (I think it was the last one though), but ever since then the automatic card detection has been taking substantially longer after each pick is chosen. Before, it was pretty much instant; now, after clicking on your card pick, the client (or just the plugin) hangs for about 5 to 8 seconds before it initializes and detects the next card choices.

I don't know if it's happening to anyone else, but I wanted to bring this to your attention just in case. Let me know if there's anything we can do to help you debug the issue. Thanks...

**Comment by rembound** [comment]
Nothing changed in the engine. Most of the changes were Tierlist updates and API changes. If you are using a plugin for Arena Helper, like the Hearth Arena plugin, it could explain the delay.

**Comment by WaxPaper** [comment]
Nope not using Hearth Arena and I don't have any other plugins for HDT installed... It's odd, because the change really was like night and day after that last update. I know what you're saying about how the update to the Tierlist and API probably wouldn't explain an issue like this, but at the same time, I can be pretty objective when it comes to trying to debug a problem, and I know something's up... It could be on my end, although the first thing I tried doing was downloading a second copy of HDT to run as a stand-alone inside it's own folder (with it's own settings instead of via the appdata path) and then tried ArenaHelper with that, but the problem still persisted...

And the 5 to 10 seconds thing wasn't an exaggeration. After I posted this thread I tried timing it to see if the "hang interval" was exactly the same after each card selection, and sure enough, it is. It's about 8 seconds. I could take a screenvid but I'm assuming you'll take my word for it. ;)

Until (or unless) we hear from other users experiencing this issue, is there anything else I can do on my end to try and diagnose the problem? One thing I didn't do was go back and check a previous version of ArenaHelper, which I'll do tonight. Otherwise do you think it could maybe be something that the guys at ACTA's (that's the source, right?) did with their API and the way it handles server requests? Maybe they either throttled something, or... I dunno... Can you think of any reason why something they did might affect the plugin in this way?

Don't get me wrong; I love the plugin and it's still perfectly usable. It's just a convenience thing; as things are now, my Arena drafts take about 10 minutes instead of 3 minutes. No big deal, but I'd like to fix it, if I can help diagnose the problem...

Thanks again, and I'll let you know if a previous version of the plugin is doing the same thing...

**Comment by rembound** [comment]
Arena Helper uses an offline tierlist, so it doesn't need server requests. One thing I can think of, would be that the cards are visually blocked in some way. If the cards are being detected, the mouse shouldn't be in the area of the cards.

If you want, you can enable a debug mode in the options. In the debug text that appears you can see more about the detected cards. Always make sure your Hearthstone window is not too small and has a normal aspect ratio.

Version v0.5.5 should still work, but really, only the tierlist file is changed. Earlier versions aren't compatible with the latest HDT due to API changes.
