### ISSUE TITLE
Plugin doesn't detect anything at all

### ISSUE THREAD

**Issue by Sombres** [rembound/Arena-Helper#41]
![hearthstone screenshot 11-07-15 13 18 55](https://cloud.githubusercontent.com/assets/15704735/11015763/b644e2ae-856b-11e5-985b-09478b39fe15.png)
The image shows the debug info. It doesn't detect neither the heroes nor the cards (after manually selecting a hero).

**Comment by rembound** [comment]
The plugin isn't correctly installed and is missing the additional dlls. Check out the "How to Install" section of the readme.

**Comment by Runer112** [comment]
I have the same issue: missing "opencv_core300" dll. I'm fairly sure I followed the installation directions correctly and installed the Visual C++ redistributable, but to no avail. Since all else failed, I even ran a search of my entire Windows directory for "opencv," but that returned no results.

**Comment by rembound** [comment]
If everything is installed correctly, you can find the opencv dlls in the ArenaHelper\x86 directory. If you open the ArenaHelper.v0.5.6.zip you can see that the directory and the dlls are present in the ArenaHelper directory.

**Comment by WaxPaper** [comment]
To the guy having the issue; make sure that after you open the plugin and are waiting for it to detect, you click on Hearthstone client window to bring it into focus (grab the title bar for a second), and then wait a couple seconds... I'm not sure if this behavior is a result of design or if it's just a problem that I have due to my end-user environment, but this is something I have to do to make sure it works. Especially on the class selection screen in the plugin; if I don't click into the Hearthstone client to bring it into focus, the plugin won't detect anything.

**Comment by Runer112** [comment]
opencv_core300.dll is definitely in the x86 directory, but I still get the error depicted in the original post.

**Comment by riQQ** [comment]
Is it unblocked (see [FAQ](https://github.com/rembound/Arena-Helper#how-to-install), if you don't know what it means).

**Comment by Runer112** [comment]
Yes, I unblocked the zip file before unzipping it. I made sure to strictly follow the installation directions.

**Comment by riQQ** [comment]
You can use Process Monitor from Sysinternals to track, where HDT tries to locate this dll. Add these filters:
![process monitor filters](https://cloud.githubusercontent.com/assets/3404787/11133052/dd5b1ae4-8993-11e5-90c1-fd702881306e.png)

**Comment by Runer112** [comment]
riQQ: I've done that, and got the following results: 

https://dl.dropboxusercontent.com/u/34812306/Logfile.PML
https://dl.dropboxusercontent.com/u/34812306/Logfile.CSV

    "Time of Day","Process Name","PID","Operation","Path","Result","Detail"
    "5:25:50.2870897 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Users\Zack\Downloads\Gaming\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86\opencv_core300.dll","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
    "5:25:50.2871359 PM","Hearthstone Deck Tracker.exe","8672","QueryNetworkOpenInformationFile","C:\Users\Zack\Downloads\Gaming\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86\opencv_core300.dll","SUCCESS","CreationTime: 6/13/2015 10:13:04 AM, LastAccessTime: 6/13/2015 10:13:04 AM, LastWriteTime: 5/13/2015 10:45:10 AM, ChangeTime: 11/12/2015 5:23:05 PM, AllocationSize: 2236416, EndOfFile: 2233856, FileAttributes: ANCI"
    "5:25:50.2871519 PM","Hearthstone Deck Tracker.exe","8672","CloseFile","C:\Users\Zack\Downloads\Gaming\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86\opencv_core300.dll","SUCCESS",""
    "5:25:50.2995288 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Users\Zack\Downloads\Gaming\Hearthstone Deck Tracker\Plugins\ArenaHelper\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.2998169 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Users\Zack\Downloads\Gaming\Hearthstone Deck Tracker\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3000414 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\SysWOW64\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3004649 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\system\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3006779 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3008935 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Users\Zack\Downloads\Gaming\Hearthstone Deck Tracker\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3019572 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Program Files (x86)\AMD APP\bin\x86_64\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3021041 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Program Files (x86)\AMD APP\bin\x86\opencv_core300.DLL","PATH NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3027464 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\ProgramData\Oracle\Java\javapath\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3030672 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\SysWOW64\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3033129 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3035381 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\SysWOW64\wbem\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3037607 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Windows\SysWOW64\WindowsPowerShell\v1.0\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3039853 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3042034 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Anaconda\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3045197 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\Anaconda\Scripts\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
    "5:25:50.3049130 PM","Hearthstone Deck Tracker.exe","8672","CreateFile","C:\bin\opencv_core300.DLL","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"

**Comment by riQQ** [comment]
Seems like the Dll is in the right place, can be opened, but is probably missing dependencies or not the correct version.

**Comment by rembound** [comment]
Try the new version, v0.6.0. It has updated dependencies and requires less dlls.

**Comment by MuFeR** [comment]
I got the exact same issue but with a different dll (cvextern.dll). I also have it in the folder but it still isn't working and I get pretty much the same error message as in the picture.

**Comment by Runer112** [comment]
Updating to v0.6.0 (and v0.6.1) gave me the same result as MuFeR: still get a missing dll error, but now with cvextern.

**Comment by rembound** [comment]
There must be some missing external dependency, like riQQ said. The dlls seem to be in the right place.

Try to install the following (maybe again):
[Visual C++ Redistributable Packages for Visual Studio 2013](http://www.microsoft.com/en-us/download/details.aspx?id=40784)

Version vcredist_x86.exe should be the right one.

**Comment by MuFeR** [comment]
I did something else before seeing your message that seems like it fixed the issue but it doesn't really make much sense. I had the deck tracker folder on an external hard drive so I moved the whole folder to my main hard disk drive. Then surprisingly it worked right away but after moving it back to the external one it still works, that's why I'm not sure if that makes sense of it it's something else.

**Comment by aizeN7** [comment]
Do this step from readme: "(8) If all else fails, copy the dlls from the x86 directory to the C: / windows / SysWOW64 directory". For me it worked, and had the same problem.
