### ISSUE TITLE
one of 3 cards is always not detected?

### ISSUE THREAD

**Issue by Zogtog** [rembound/Arena-Helper#43]
Plugin shows a short line intead of value of a card after the update.

**Comment by Zogtog** [comment]
Ops, the same issue as here https://github.com/rembound/Arena-Helper/issues/42.

**Comment by rembound** [comment]
The short line shows when there is no tier score available. The card was probably detected, but the tier list doesn't have the new cards yet. When the new tier list becomes available, I will update the program.

**Comment by Zogtog** [comment]
It seems that plugin detects line-flagged card not correctly. Actual card doesn't match with card shown in Arena Helper window.

**Comment by rembound** [comment]
Make sure you are using the latest version. The plugin updated a couple of days ago to support the new cards.

**Comment by Zogtog** [comment]
As i mentioned in my first message, errors occured after 0.6.0 update. By the way, it doesn't recognize classic cards, not new ones from the The League of Explorers expansion.
