### ISSUE TITLE
Plugin - Doubt !!! PLZ HELP

### ISSUE THREAD

**Issue by aizeN7** [rembound/Arena-Helper#45]
Can someone help me? Went the last update helper arena, there are three files, I have to unpack the three and put in HDT (in the plugin folder)? Or just the first download?

Sorry bad english

![print](https://cloud.githubusercontent.com/assets/15863373/11242597/d4e540d8-8de9-11e5-9ceb-a059fba721ce.jpg)

**Comment by riQQ** [comment]
You only need the first file. Extract these files to `<HDT directory>\Plugins\ArenaHelper`.

**Comment by rembound** [comment]
I've updated the readme.

> 1) Download the latest ArenaHelper.zip from the releases page

**Comment by aizeN7** [comment]
In fact, after making the next step from readme: "(8) If all else fails, copy the dlls from the x86 directory to the C: / windows / SysWOW64 directory", it worked: D

Ty
