### ISSUE TITLE
Unable to Install Correctly

### ISSUE THREAD

**Issue by skippygammons** [rembound/Arena-Helper#48]
Followed directions:
Downloaded
Unblocked
Unzipped
Folder was missing "MSVCP120.dll"
Followed directions for correction - Used link to Download and Install "Redistributable Package"
tried to install and was given  "Uninstall, Repair, Close" 

The above options are making me nervous that I'm doing something to this computer that may compromise it. I checked the folder for the "MSVCP120.dll" File and couldn't locate it.

What should I do?

**Comment by rembound** [comment]
The Redistributable Package is an official Microsoft software package, so you don't need to worry about potential dangers. It looks like you've already installed it, so you would see the message.

If you open the Zip-file directly, you can see all of the files and directories that should be unzipped into the HDT plugins folder. The "x86" directory contains the file "msvcp120.dll".

For other potential solutions, check out issue #41
