### ISSUE TITLE
[Suggestion] Detection in window-mode?

### ISSUE THREAD

**Issue by alex9801** [rembound/Arena-Helper#49]
Title.

And also, if the plugin only supports fullscreen detection, I think it would be nice to mention it somewhere in the description or "about" session.

Thank you!

**Comment by riQQ** [comment]
Detection in windowed mode is working for me. Try setting a resolution in Hearthstone, if the box is empty.

**Comment by Ansem93** [comment]
I used it today, it works fine on windows 10

**Comment by alex9801** [comment]
I tried in 1024x768, low quality, windows 7 x86 environment, and didn't work..
Maybe I should reinstall the plugin.

Thank you for the comments!
