### ISSUE TITLE
Requests: Manual hero picking, inbuilt overlay, save deck to arena

### ISSUE THREAD

**Issue by ekohilas** [rembound/Arena-Helper#5]
Please allow a way to manually pick your hero. I had to manually edit the file as I had already picked a hero before hand.

I had a vision of this type of plugin, and I am amazed you guys managed to do it.
I think the next step would be to make this into an overlay like HDT, and have the numbers for each card appear at the bottom of each card, with a colour overlay scale

also saving a deck appears in normal decks, not in arena decks

nevertheless, good job on the work :D

**Comment by rembound** [comment]
Overriding picks is something that could be added. I didn't want to clutter the user interface too much with extra buttons, like forward/backward buttons.

I have been thinking about adding an overlay. Adding an overlay, while the Arena Helper window is open, is no problem. If the plugin would only have the overlay, without the external window, you might lose some functionality.

A saved deck indeed appears in the constructed decks. Thanks for pointing that out. I added an Arena tag, but failed to add the Arena flag when constructing the deck.

**Comment by ekohilas** [comment]
I feel like there is no need for a window all together, the whole functionality of the plugin can be in an overlay, and if the window is really needed It should be as small as possible, it would make the app less cluttered.
Again, this is just my own opinion :)

**Comment by rembound** [comment]
The new version includes manual hero picking and a better overlay.
