### ISSUE TITLE
No HearthstoneDeckTracker/Plugins in my hearthstone decktracker file :/

### ISSUE THREAD

**Issue by Lightextinct** [rembound/Arena-Helper#50]
Im trying to get this awesome looking plugin but in my hearthstone decktracker files there is no plugin folder >:U 
![screenshot 281](https://cloud.githubusercontent.com/assets/16214983/11670468/cfbaf382-9db6-11e5-91c1-5ab8a1511247.png)

Is there a way to fix this?

**Comment by rembound** [comment]
Manually create a new "Plugins" folder and unzip the plugin to it.
