### ISSUE TITLE
Cards not being detected correctly

### ISSUE THREAD

**Issue by cgordoncarroll** [rembound/Arena-Helper#51]
It looks like the wrong hash is being calculated, but I did verify that all .dll's are properly installed. 

This is on Windows 10 Pro.
![wrong hashes](http://i.imgur.com/Lb5piel.jpg)

**Comment by rembound** [comment]
Check out issue #42. I currently don't know what causes this problem.

**Comment by cgordoncarroll** [comment]
Understood. v0.6.3 worked for me just fine until this yesterday evening. I thought flux might be affecting it, but the issue persists either way. 

I had Windows install an overnight upgrade and that might be related to this issue. Unfortunately, I'm not able to see what updates were actually installed, but hope it helps.. :unamused:

**Comment by ginko147** [comment]
Have same problem. Latest version of this plugin doesn't detect correctly my arena cards. I also disabled flux as well and didn't fix anything. I'm using WIndows 10 Home x64 with latest updates.

**Comment by czar** [comment]
Also having this issue, Win 10 w/ latest Arena Helper/HDT.

**Comment by whatdoesdfoxsay** [comment]
Also having this issue with v0.6.4 on W7 x64.

**Comment by riQQ** [comment]
Did you delete the ArenaHelper Plugin folder before copying the new version?

**Comment by whatdoesdfoxsay** [comment]
@riQQ This is the first installation of the ArenaHelper plugin on this machine, so a previous version of the folder did not exist.

**Comment by czar** [comment]
@riQQ I just removed the ArenaHelper folder and copied the newest version, but issue is not resolved.

**Comment by miggat** [comment]
Same problem with v0.6.4 on W8.1 x64

**Comment by rembound** [comment]
Try setting the quality of the game graphics to "High".

**Comment by czar** [comment]
@rembound I'm running HS on High by default, tried all the other settings too, Low/Medium and or full screen vs windowed.  Issue was not resolved after verifying the High setting or trying other settings. :(

**Comment by miggat** [comment]
Same as czar, i've tried with every possible graphic option with no luck. The plugin recognizes cards, but all of them are wrong. 
Would it help to upload a screenshot of the debug info?

**Comment by rembound** [comment]
I might have found the problem. I've updated the data files, which will work with the latest HDT. Just let the plugin auto-update the data files.

**Comment by czar** [comment]
@rembound Yes it's working again :+1: Thanks.

**Comment by miggat** [comment]
Updated HDT and let Arena Helper download new files automatically and it's working perfect now! Thanks rembound, that was fast!

**Comment by whatdoesdfoxsay** [comment]
@rembound Thank you! The issue is resolved for me as well. Running perfectly on W7 x64.

**Comment by cgordoncarroll** [comment]
This issue was fixed some time ago, closing.
