### ISSUE TITLE
tierlist 0.1.2 Eerie Statue has no value (should be 8)

### ISSUE THREAD

**Issue by HoopyHobo** [rembound/Arena-Helper#52]
[Here's my source for values](https://www.reddit.com/r/GrinningGoat/comments/3wayak/tier_list_loe_full_12102015/). Also, Elise Starseeker is supposed to have a value of 48 for Warlocks. In [Adwcta's Google doc](https://docs.google.com/spreadsheets/d/10jPQERiCZvBfRCZqCAMyk9ge-7OdlE4JZU1-CVpRrug/edit#gid=1849768973) it has green text to indicate that the card is rated above the base value for Warlocks, but by mistake the value isn't any different.

**Comment by rembound** [comment]
Thanks for the report. The errors were actually in the Tier List doc itself.
Eerie Statue wasn't updated, but they have added it now. Elise Starseeker still has the wrong value. Maybe you could send them the bug-report.

I've updated the tier list with the official numbers. Unfortunately this means the Warlock value is still wrong.
