### ISSUE TITLE
unable to load cvextern.dll

### ISSUE THREAD

**Issue by PrBooty** [rembound/Arena-Helper#53]
unable to load cvextern.dll
![error](https://cloud.githubusercontent.com/assets/16336021/11869269/e0590512-a4d7-11e5-9545-6511cea3eb8a.jpg)

**Comment by rembound** [comment]
For possible solutions, check out issue #41.

**Comment by PrBooty** [comment]
Mb I can place some where else this dlls, coz I have a windows Vista, and I dont have this C:/windows/SysWOW64 directory.

**Comment by rembound** [comment]
Try `C:\Windows\System32`
If you have installed HDT on an external HDD, try installing on a local hard disk.

**Comment by PrBooty** [comment]
Yes. I done it before. Still not help
