### ISSUE TITLE
Shows wrong card selection 

### ISSUE THREAD

**Issue by domas9636** [rembound/Arena-Helper#58]
![untitled](https://cloud.githubusercontent.com/assets/16404257/11961447/5eba67f4-a8e1-11e5-89bc-e79e46e31b80.png)
In debug it seems that card names are right but selection shows wrong. Tracker and addon just deleted and  added again today (problem is for week or more)

**Comment by rembound** [comment]
Try to click the "new arena" button and manually select a hero by clicking the portrait icon in the top-left. This will reset the detected cards. HDT updated and changed the card indices.

**Comment by Battleheart** [comment]
I'm also having an issue where card detection is wrong. did the "new arena" trick but didn't change anything.
![arena-helper-debug](https://cloud.githubusercontent.com/assets/16798979/12702275/0d3bbcea-c7f2-11e5-90a5-f51f9d43ccdd.jpg)

**Comment by rembound** [comment]
Update to the latest version: https://github.com/rembound/Arena-Helper/releases
