### ISSUE TITLE
Stuck at "Detecting Arena..."

### ISSUE THREAD

**Issue by FerrisWheelJunkie** [rembound/Arena-Helper#59]
I have read through all the issues already listed below, and I still cant seem to get this to work.

I have taken a screenshot of the debug mode, maybe there is something I am missing?
I have tried:
-  disabling / enabling the plugin
- numerous restarts
- unlocking all the .dll files
- copied the .dlls from the x86 directory to the C:/windows/SysWOW64 directory
- reinstalled Visual C++ Redistributable Packages for Visual Studio 2013
- tried a few different resolutions, mostly I play in full screen, 1920 x 1080, but have tried using 1280 x 960, both full screen and windowed, this doesn't seem to make a difference.

I don't have an "opencv_core300.dll" in the x86 folder in the Arena helper folder, but that doesn't seem to be the issue in the debug message, it seems to be with "cvextern.dll" which does exist.

What am I missing?
![debug](https://cloud.githubusercontent.com/assets/16441907/12005345/254d313e-aba9-11e5-9165-0130550e0e9b.jpg)

**Comment by rembound** [comment]
If it was installed on an external HDD, try to install on a main drive. See issue #41

**Comment by FerrisWheelJunkie** [comment]
Hi.

No luck, it wasn't ever installed on an external HDD. In fact I just unzipped deck tracker and placed the folder on my desktop. The plugin I placed in the plugin folder in the HDT directory, and enabled it.
HDT tracker works fine.

Dam, I really wish I could get this working, it would be amazing!

**Comment by PrBooty** [comment]
Same problem

**Comment by FerrisWheelJunkie** [comment]
I managed to fix this yesterday.

I re-downloaded the Arena helper files, and deleted the old ones.
I then copied the 3 .dll files from "C:\Program Files (x86)\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86" and pasted them into "C:\Windows\SysWOW64"

After that it worked!

**Comment by Xion1310** [comment]
Is this for 64bit only ? I cant seem to find "C:\Windows\SysWOW64" in my Wins 7 32bit.

![untitled](https://cloud.githubusercontent.com/assets/16665946/12263203/d1334d26-b95f-11e5-8be3-924919ed29a4.png)

Can anyone help me with this problem ? I've tried everything i could. Thanks.
Btw its not like that just because i didnt get into Arena, the picture is to show the error. I did run the game in 1280 x 960 and started a new arena.

**Comment by FerrisWheelJunkie** [comment]
Hi Xion1310.

Yes I was using windows 7 - 64 bit.
I presume you would be looking for something similar for 32 bit, possibly "C:\Windows\System32" 
I'm not 100% certain, but it could be there, its been a while since I used a 32-bit system.

Good luck.
