### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by Krishov92** [rembound/Arena-Helper#6]
Hello! Whenever I try to detect an Arena, it starts by trying to detect a new Arena run, then it waits for like 5 seconds before a pop-up shows up, telling me I'm missing a .dll-file called MSVCP110.dll. I have to click "Ok" on the pop-up box 16 times before it disappears completely. Then, if I try start it again, it's stuck on detecting heroes for eternity.
I've already tried downloading it and putting it in the plugins-folder, but it still won't work. Do you have any tips to help me?

**Comment by Epix37** [comment]
Try placing MSVCP110.dll in C:/Windows/system32 instead of the plugins folder.

**Comment by Krishov92** [comment]
I thank you for the quick response!
I tried putting it into C:/Windows/system32 but without luck - it still shows up as an error and tells me to try to re-install the program. Would it help if I restarted my computer? I could take a screenshot with the error-pop-up if you'd like.

**Comment by Epix37** [comment]
With system32 stuff, restarting often helps, yea.

**Comment by Epix37** [comment]
If you still have the problem, this will hopefully help: http://fixpcnyc.com/msvcp110-dll-is-missing-from-your-computer-error-fixed/

**Comment by Krishov92** [comment]
Alright, so, I tried restarting and that didn't help. I tried the guide though, but unfortunately that didn't help either. I don't know if I should just give up, because to me it's not that big of a deal, if it doesn't work. I mean, I would love for it to work properly, but it's OK if it doesn't. :+1:

**Comment by divtarion** [comment]
I have the same problem

**Comment by arjones2009** [comment]
I also have this problem.  Has anyone found a fix that works?

**Comment by rembound** [comment]
Try installing the [Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784). Try the x64 or x86 version.

**Comment by mrobinet** [comment]
I have the same problem. I installed the Visual Studio redist package for 2013 and it didn't appear to help me either.

**Comment by rembound** [comment]
Maybe I have found the right version:
http://www.microsoft.com/en-us/download/details.aspx?id=8328
http://www.microsoft.com/en-us/download/details.aspx?id=13523

**Comment by rembound** [comment]
Please let me know if this worked. If it does, I can update the installation instructions.

**Comment by mrobinet** [comment]
As a quick hack I droppped the MSVCP110.dll into the DeckTracker folder and it resolved the error for me. Unfortunately I have yet to get it to detect my arena decks.

**Comment by rembound** [comment]
Added instructions to the README. The new version needs a newer Redist, which should already be included in the x86 directory.
