### ISSUE TITLE
The current build number is not shown in the window

### ISSUE THREAD

**Issue by VeXHarbinger** [rembound/Arena-Helper#60]
Howdy,
First off, excellent job I love this tool.  I was getting the issue where the cards were being detected incorrectly so I decided to download the code and re-apply.  In doing this I realized I was a few builds behind.  The error of course is on my part, I just couldn't find the build number to tell.  Just thought it could be useful, if you could add it to the window so it's easy to tell.

**Comment by rembound** [comment]
The main problem was that the auto-update function would only run if a specific condition was met. I have changed it in the latest version, which will now always check for updates at the start of the plugin.

It is a nice suggestion however, to display the build number somewhere in the plugin.

**Comment by rembound** [comment]
Added the version number to the about screen.
