### ISSUE TITLE
Plugin not being detected 

### ISSUE THREAD

**Issue by cschafer** [rembound/Arena-Helper#61]
I download the zip, unblocked it, started HDT, went to options, went to plugins, went to tracker, went to plugins, and it's not showing up. I have other plugins and i can see them but i can't see Arena Helper

**Comment by rembound** [comment]
Make sure to follow the steps in the installation instructions:
>- Unzip the archive to Hearthstone Deck Tracker/Plugins
>- If you've done it correctly, the ArenaHelper directory should be inside the Plugins directory. Inside the ArenaHelper directory, there should be a bunch of files, including a file called ArenaHelper.dll.

**Comment by cschafer** [comment]
![error 3](https://cloud.githubusercontent.com/assets/11575138/12304359/29138e64-b9fd-11e5-9006-7cc548e51a67.png)

I do have ArenaHelper.dll in the directory

**Comment by riQQ** [comment]
Move the ArenaHelper folder one level up. The result should be `Hearthstone Deck Tracker\Plugins\ArenaHelper\`.

**Comment by cschafer** [comment]
That worked. Thank you very much
