### ISSUE TITLE
Update message directs to master directory instead of 0.6.5 release page

### ISSUE THREAD

**Issue by drsecond** [rembound/Arena-Helper#64]
I had installed the Arena Helper plugin without incident, and was happily using it.  I received an alert to download an update.  The page I got directed to (https://github.com/rembound/Arena-Helper) is the page for the master files.  I tried downloading the zip on that page, but it does not contain a dll.   After banging around for a couple days, I finally determined that I need to get to the release page (https://github.com/rembound/Arena-Helper/releases).  I think this will be confusing for many users, so changing the path on this "update" link is probably a very good idea.

**Comment by rembound** [comment]
The [how to install](https://github.com/rembound/Arena-Helper#how-to-install) section on that page directs the user to  the releases page. On the main page, you can also see an overview of the plugins that can be installed. GitHub did change their user interface some time ago, which makes the releases-button a bit more confusing.
