### ISSUE TITLE
UnResponsive Card Picking/GUI Updating

### ISSUE THREAD

**Issue by NvrBst** [rembound/Arena-Helper#65]
Seems similar to issue #40. Whenever I pick a card it sometimes takes Arena Helper very long to display the next card value choices. Based on the log messages, to me, it seems like it always detects the cards+values very fast, but after telling the screen to update, the screen update doesn't show up immediately. AKA the delay is between the SearchCardValues() and "Added new card to arena deck" (HDT msg). It looks like arena helper/hdt is very laggy and uses max cpu (25%) after I pick a card which is probably why the gui overlay update ("Gettings Values..." to "**_Actual Values**_") takes so long to display.

**Me Guessing:**
I see inside SearchCardValues() there is a "arenawindow.Update();", maybe something has to be done after this to allow the screen to update immediately before it tries to WaitCardPick() just to make sure that the screen is updated with the new data, aka, transitions from "Getting Values...". My guess is that the screen wants to update with the new data, but, application is so cpu-busy in WaitCardPick() (calculating phashes?) that it sometimes takes a while for the application to process the main gui thread events to actually update the screen at larger resolutions. AKA maybe something like this would at least update the screen immediately:

arenawindow.Update();
Application.DoEvents();   <--new

**Better Fix**
If your able to reproduce, whatever code is causing the max cpu to occur should be done on a background thread or have it release time to the main gui thread after every loop. I'm assuming there is some cpu-heavy code related to WaitCardPick() (calculating screenshot phashes?) and this cpu-heavy work scales the higher the resolution gets.

**Extra Information:**
My screen resolution is 3200x1800. I typically want to play the game in windowed 2304x1440. At this resolution (or most/all resolutions I tested around this) produces the issue. If I play the game at windowed 1600x900 then I have no issue. Maybe for #40 he upped his resolution as well? Initially I thought this was normal Arena Helper behavior (delay being a network call or something, note: I know now it's a local db), until I play'ed on my laptop once and it was pretty much instant during the entire arena draft. Eventually I figured out the the factor was the game resolution I was playing at.

At 1600x900 everything is pretty instant. Maybe one out of 30 cards takes ~6s to transition from "Getting Values..." to showing the values, but most times it's 1-2s.

At 2304x1440 about 20% of time time it takes 30s to transition from "Getting Values...". Then 40% it takes 5-8s, 40% it takes ~2s.

Let me know if you want log files or like me test something. Thanks.

**Comment by rembound** [comment]
Will have to look into this.. a large resolution might make the phash calculations expensive.
