### ISSUE TITLE
Can't get hearthstone deck tracker to recognize it

### ISSUE THREAD

**Issue by Award30** [rembound/Arena-Helper#66]
Hi, it looks like the newest release may have different instructions (for example arenahelper.dll is not in the new package). I just installed hearthstone deck tracker and arena helper today for the first time and the plugin is not recognized. I ensured that I unblocked (and applied). Then I extracted to the plugin folder. The mscvp folder was not there, so I downloaded the C++ thing. Still not recognized. I couldn't find the x86 folder, so I deleted everything in the plugins folder and downloaded the 0.6.5 version. Not recognized, but now the instructions made sense, so I tried copying the x86 folder, but my computer wouldn't let me put them in the syswow folder (I think, my directory isn't in the same location). I'm not technologically savvy, so I'm scared to try to work around this. Any troubleshooting suggestions?

Thanks

**Comment by rembound** [comment]
Make sure to download the ArenaHelper.v0.6.6.zip from the [releases](https://github.com/rembound/Arena-Helper/releases) page.

**Comment by Award30** [comment]
That was the first release that I tried. None of them are recognized by HDT for me.

**Comment by rembound** [comment]
If you followed the installation instructions correctly, you would have the ArenaHelper.dll in the following location together with a bunch of other files and directories: `Hearthstone Deck Tracker\Plugins\ArenaHelper\ArenaHelper.dll`

As in step 7 of the instructions, you need to enable the plugin in the HDT settings:
> Launch Hearthstone Deck Tracker. Enable the plugin in `Options -> Tracker -> Plugins`.

**Comment by CasereHG** [comment]
I have the same issue as the OP. I have Windows 10. I have the latest versions of HDT and Arena Helper. I downloaded and installed the x86 files. But, no DLL file for the plugin. I still have my old directory of ArenaHelper which does show the plugin and does load up in HDT. I followed the instructions exactly as written, step by step, but no DLL file. If it makes any difference, I used 7-Zip to extract the file (although I did try with WinZip as well but had the same result).

**Comment by rembound** [comment]
Open the `ArenaHelper.v0.6.7.zip` with 7-zip to see the contents. All of the files that are needed are there. If files are missing, maybe a virus scanner or something else modified the zip.

**Comment by rembound** [comment]
I think you've downloaded the wrong zip.
Check out the [Installation instructions](https://github.com/rembound/Arena-Helper#how-to-install). The zip you need is located at the [releases](https://github.com/rembound/Arena-Helper/releases) page.

Here is a direct link: [Arena Helper v0.6.7](https://github.com/rembound/Arena-Helper/releases/download/0.6.7/ArenaHelper.v0.6.7.zip)

**Comment by CasereHG** [comment]
Yes, I downloaded from the ZIP button on the main page. I didn't know enough about Github that I should go to the releases web page. Maybe, if someone like me who missed it, you could point people to the releases web page and not to use the ZIP button? Thank you very much for taking the time to help me! I'll make sure that I point people in the correct direction!

**Comment by rembound** [comment]
Updated the readme to be more clear.
