### ISSUE TITLE
[HDT v0.13.11] Freezes after "Arena Helper: loading data"

### ISSUE THREAD

**Issue by azeier** [rembound/Arena-Helper#68]
I think I managed to break it with the new update after all :(. I tried so hard.

No crash, nothing else in the log, HDT and the Arena Helper window just freeze when Hearthstone is running.

**Comment by bazukamos** [comment]
i  think i have the same problem, when i open the Arena Helper it freezes and i can only close trough task manager.
![arena helper crash](https://cloud.githubusercontent.com/assets/15827042/13130763/564c6db8-d5de-11e5-9cfb-d7e041149bdf.jpg)

**Comment by showmethebitcoin** [comment]
Same here, I think the update to the main HDT app broke it.

**Comment by showmethebitcoin** [comment]
I restored Hearthstone Deck Tracker to 0.13.9 for now and it's working again. It's a good workaround if you want to run some arenas.

**Comment by rembound** [comment]
Thanks for the reports!
HDT v0.13.11 changed the `CaptureHearthstone` function which resulted in a crash. I've updated Arena Helper to use the old function `CaptureScreen` directly.

**Comment by Epix37** [comment]
What's the exception? The method signature should still be the same :/.

**Comment by rembound** [comment]
I can't get an exception out of it. It freezes before handling the exception.

**Comment by Epix37** [comment]
Very strange...

**Comment by rembound** [comment]
It's probably some threading issue.

**Comment by gabrielhpugliese** [comment]
I see the problem as well. I can only close it on process manager.

**Comment by rembound** [comment]
@gabrielhpugliese The latest release fixes the problem.

**Comment by gabrielhpugliese** [comment]
Thanks!
