### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by pudgyasian** [rembound/Arena-Helper#69]
Sorry for the post, I tried everything, but I just don't know that much about computers.  I tried to follow the steps.  I unblocked the file before unzipping it.  But there is no Arenahelper.dll.  I tried the first fix which was to download the Redistributable Package.  I downloaded the right one 86 one and it still didnt show up, although I don't really know what to do after I run the installer and it repairs something.  I have done this a few times and I have run out of things to do.  I don't know where the debug mode in options window is don't know where to find it and I have no idea what the last step means.  Sorry for the bother.  I downloaded ArenaHelper before the HDT update and it worked, but now it doesn't :(

**Comment by CasereHG** [comment]
I had the same issue as well. The author of the plugin is awesome and pointed out the issue. You have download from https://github.com/rembound/Arena-Helper/releases instead of the ZIP button on the main page.

**Comment by pudgyasian** [comment]
Thank You, It works perfectly now.
