### ISSUE TITLE
Arena Helper window doesn't appear

### ISSUE THREAD

**Issue by MMcCormick** [rembound/Arena-Helper#7]
I have installed the plugin successfully (Windows 7 SP1 running in bootcamp on a 2013 macbook pro). However, even though the Arena Helper window opens (I can see it in my taskbar and when alt-tabbing), the window itself does not appear anywhere on the screen.

I have fiddled with a few settings and reinstalled the plugin. Any ideas?

**Comment by corlettb** [comment]
I've had a similar issue where I've needed to change the window position after switching around my resolutions. 

Try opening up:
C:\Users\<username>\AppData\Roaming\HearthstoneDeckTracker\ArenaHelper\arenahelper.json

and zero the position values.

**Comment by rembound** [comment]
You can also remove the arenahelper.json completely. It will be regenerated.

**Comment by MMcCormick** [comment]
Deleting worked! Thanks very much.
