### ISSUE TITLE
Problems with adding the plug in

### ISSUE THREAD

**Issue by RyuzakiBlade** [rembound/Arena-Helper#70]
I followed the instructions on the site https://github.com/rembound/Arena-Helper  and still can not access the plug in. It does not show up at all in the plug in list (on the app home and in the settings).

Here is the most recent log as well:

http://pastebin.com/7RsaLY13

**Comment by riQQ** [comment]
Could you post a screenshot of your plugin folder?

**Comment by RyuzakiBlade** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/17595302/13478946/a324c298-e0a1-11e5-9548-e01790e8f2ce.png)

**Comment by riQQ** [comment]
This looks fine. Another screenshot of the content of the plugin folder?

**Comment by RyuzakiBlade** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/17595302/13480948/77b0f538-e0af-11e5-8c12-9ba7aec576a9.png)

**Comment by riQQ** [comment]
The folder structure is alright. Did you unblock it as described? Have you tried starting HDT as Administrator? Have you tried moving HDT to another place (away from the Desktop folder)?

**Comment by rembound** [comment]
HDT can't find plugin dlls when they are in nested directories. Move the ArenaHelper directory directly inside the Plugins directory. You can then remove the ArenaHelper.v0.6.7 directory.

See step 5 of the installation instructions:
> If you've done it correctly, the ArenaHelper directory should be inside the Plugins directory. Inside the ArenaHelper directory, there should be a bunch of files, including a file called ArenaHelper.dll.

**Comment by RyuzakiBlade** [comment]
Thanks for the help!
