### ISSUE TITLE
Wrong Detection of Recruiter

### ISSUE THREAD

**Issue by Ronker** [rembound/Arena-Helper#72]
Hello,
I encounter a wrong detection of Recruiter. It showed up as Priestess of Elune. I guess it doesn't show up very frequently, so the detection isn't perfect. 
![2016-03-09](https://cloud.githubusercontent.com/assets/17747855/13642686/c97430f6-e61d-11e5-9b0e-28e9560f62eb.png)

Thank you and keep up the great work!

**Comment by rembound** [comment]
Detection isn't always 100% indeed. Different resolutions and aspect ratios can also mess with detection. Thanks for the report!
