### ISSUE TITLE
Big Hero detection is not working

### ISSUE THREAD

**Issue by riQQ** [rembound/Arena-Helper#74]
On a new arena run all three heroes are detected correctly and displayed in the ArenaHelper window. After clicking a hero in Hearthstone, ArenaHelper switches back to the `Detecting arena` screen. HS is in windowed mode with a resolution a little below 1920 x 1200.
Do you need any additional information?

**Comment by rembound** [comment]
I didn't get this problem when I just tested it, so I guess nothing changed, except for the new hero that isn't supported yet. I think it should not interfere with the rest of the picking process, because the heroes are picked by reading the log files.

**Comment by riQQ** [comment]
It has been working since I started using Arena Helper until January 26th. After that i didn't draft a new arena, so i can't exactly tell, when it stopped working.

**Comment by riQQ** [comment]
It always invalidates the arena when I click a hero portrait (https://github.com/rembound/Arena-Helper/blob/master/Plugin.cs#L1418).

**Comment by rembound** [comment]
Try enabling the debug mode in the options and post a screenshot, this will tell if it can detect the arena correctly.

**Comment by riQQ** [comment]
![before](https://cloud.githubusercontent.com/assets/3404787/14060679/094c582e-f36c-11e5-9632-a065b9de879f.png)
![after](https://cloud.githubusercontent.com/assets/3404787/14060680/094dc9f2-f36c-11e5-8f58-de8d477221f4.png)

**Comment by rembound** [comment]
In the second screenshot, arenacheck2 should be smaller than 10. The smaller this number, the more perfectly the detection was. Try changing the aspect ratio or window size. But as I said, selecting the hero now should not interfere with the rest of the picking process.

**Comment by riQQ** [comment]
Changing aspect ratio solved my problem. Is there any way to make this work better for all aspect ratios?
