### ISSUE TITLE
It does not start Arena Helper v0.6.8 error occurs.

### ISSUE THREAD

**Issue by Roman-Omsk** [rembound/Arena-Helper#75]
Good afternoon! It does not start Arena Helper v0.6.8 error occurs.

Error picture posted here.

http://s019.radikal.ru/i643/1603/f9/0b6599435843.jpg

help fix the `problem.

I think the error due cvextern.dll

but I could be wrong, tell me what is the error?

**Comment by Roman-Omsk** [comment]
![error](https://cloud.githubusercontent.com/assets/18092765/14062495/2ff2b252-f3cb-11e5-9a06-7878344d3ccf.jpg)

**Comment by rembound** [comment]
Yes, this is an installation error. Make sure to follow the instructions at: [how to install](https://github.com/rembound/Arena-Helper#how-to-install).
More info: Issue #53, #41 and #59
