### ISSUE TITLE
Crashing with latest HDT

### ISSUE THREAD

**Issue by fmoraes74** [rembound/Arena-Helper#76]
Arena Helper crashes immediately when using the latest HDT:

[Crash report 542016-1922.txt](https://github.com/rembound/Arena-Helper/files/206925/Crash.report.542016-1922.txt)

**Comment by rembound** [comment]
Open up %appdata% in windows explorer and go to the `HearthstoneDeckTracker\ArenaHelper\` directory. Go into the `Decks` directory and delete the json file with the latest date. Alternatively, delete the entire `Decks` directory.

If it doesn't work, try deleting the HDTAHPlugin from the `Hearthstone Deck Tracker\Plugins\ArenaHelper\plugins` directory and see if it works.

**Comment by fmoraes74** [comment]
That seems to have resolved the problem (deleting the latest JSON file). Can you explain what went wrong by any chance? I didn't save the file though.

**Comment by rembound** [comment]
Some data in the file must be corrupted. Maybe because of a crash or something else.
