### ISSUE TITLE
Detection with Lady Liadrin isn't working

### ISSUE THREAD

**Issue by riQQ** [rembound/Arena-Helper#77]

**Comment by rembound** [comment]
This is correct. It won't interfere with picking however, this is just cosmetic. Getting the source hashes of the alternative and golden heroes is not as easy as getting the card hashes. The hashes need to be generated from within the game.

**Comment by riQQ** [comment]
Is there a way to get you that hash?

**Comment by riQQ** [comment]
Posted them at #15.

**Comment by rembound** [comment]
Thanks! Added them to the new release.

**Comment by riQQ** [comment]
Works fine, thanks.
