### ISSUE TITLE
Weird advised choice

### ISSUE THREAD

**Issue by ubloh** [rembound/Arena-Helper#79]
It seems the highlighted card isn't the one with the best score.
Is it the intented behaviour?
![capture](https://cloud.githubusercontent.com/assets/578176/14427417/f265ee32-fff4-11e5-95f5-9386765f6c28.PNG)

**Comment by ubloh** [comment]
It happened again. The issue might be the score of HearthArena having only one decimal but that may come from the HA plugin then.
![capture](https://cloud.githubusercontent.com/assets/578176/14427716/41137080-fff6-11e5-8110-bd0af41b16f8.PNG)

**Comment by ubloh** [comment]
Also with no decimal at all.
![capture](https://cloud.githubusercontent.com/assets/578176/14438593/22fa359e-0027-11e6-8609-e49804bb62ab.PNG)

**Comment by rembound** [comment]
Thanks for the report!

This is a known problem with the HA plugin. I have reported the issue to the plugin developer before with a code solution here: [Value format problems](https://github.com/corlettb/HDTAHPluginHAPlugin/issues/2)

I have attached the fixed plugin here, just replace the original:
[HDTAHPluginHAPlugin.0.0.6-fixed.zip](https://github.com/rembound/Arena-Helper/files/214641/HDTAHPluginHAPlugin.0.0.6-fixed.zip)

**Comment by ubloh** [comment]
Thanks for the quick fix though the issue didn't come from your end.
Hopefully the original programmer will continue to maintain his plugin...
Thanks again!
