### ISSUE TITLE
Arenahelper doesnt work and makes the HSDT "crash" completely

### ISSUE THREAD

**Issue by FiremanSammy** [rembound/Arena-Helper#80]
When i start Arenahelper, it opens the little AH window most of the times, but after that, nothing works anymore. AH and also the normal HSDT dont react to anything and can only be closed by taskmanager. Sometimes not even the AH window opens, everythings just not reacting on clicks anymore. I tried the suggestions from the issue report "Crashing with latest HDT #76" - after deleting the newest json file, it showed the option to update Arenahelper, but after that - the same nothing-is-working-problem. I deleted again, denied the update - same. Those were the only times the update option came on, any other attempt just made everything not working. Sometimes it lets me click on "new arena", but then...same problem.

**Comment by rembound** [comment]
I hope you got it working, probably by updating to the latest version.
