### ISSUE TITLE
"New update available!" when using latest release

### ISSUE THREAD

**Issue by FlamingFox911** [rembound/Arena-Helper#81]
Title says it all. The notifies of a new version when I am using 0.7.0 already.

**Comment by rembound** [comment]
If you click the support button in the plugin, you can check which version you are running.
If the tier list was updated, you would get a notification as well.

**Comment by FlamingFox911** [comment]
It says v0.6.9 but I downloaded the v0.7.0 release zip and merged it into the ArenaHelper folder.

**Comment by rembound** [comment]
Make sure to download the correct zip and overwrite the files. I just checked and the [latest zip 0.7.0](https://github.com/rembound/Arena-Helper/releases/download/0.7.0/ArenaHelper.v0.7.0.zip) has the correct version number.

**Comment by FlamingFox911** [comment]
Okay. I found one issue. Apparently with the big update to HDT, it reset some setting that I had made, including saving config and data in AppData folder. Apologies.

**Comment by rembound** [comment]
No problem! I'm glad it works.
