### ISSUE TITLE
Field not found

### ISSUE THREAD

**Issue by aljlue** [rembound/Arena-Helper#82]
I get the following error in debug mode:
"Field not found: Hearthstone_Deck_Tracker.Hearthsthone.Card.Id"

Is this problem related to the new patch or to version 0.7 ?

**Comment by JustDominik** [comment]
Same problem here... but I got Deck Tracker and Arena Helper for the first time today so I don't know if I did something wrong or there is a problem with the new patch ^^
(The software recognizes the Hero but no cards)

**Comment by riQQ** [comment]
It's a problem with the new patch.

**Comment by rembound** [comment]
I'm waiting for the new HDT update at the moment to update the new card info.

**Comment by MSHalcyon** [comment]
# Fix for now:
Use not the pre-release build, but the release-build and everything works fine!!!
