### ISSUE TITLE
doubling card during picking

### ISSUE THREAD

**Issue by bombek92** [rembound/Arena-Helper#83]
During card picking when i click on card it doesn't pick but Arena Helper recognises as it would have been picked and moves to the next card (which duplicates because I do not have picked it yet). This ends up having a few duplicates and finishing my draft before it actually is finished.

**Comment by rembound** [comment]
Try delaying your new picks until you see that the Arena Helper window recognized the new cards, it could be that you are picking too fast.

**Comment by bombek92** [comment]
Hi, thank you for your suggestion but I know about the delay and I always wait until it is ok, I have this issue on the newest update. It's not that ArenaTracker doesn't pick card but in-game it is picked it is opposite - ArenaTracker picks it but in game nothing happenes. So i have to click another time and I have twice the card in ArenaTracker.

**Comment by rembound** [comment]
[Arena Helper](https://github.com/rembound/Arena-Helper) uses the Hearthstone log files to pick cards, which means that any detected pick was already picked by the game itself first. Make sure you are using Arena Helper.
