### ISSUE TITLE
Window Freezes - Cant do/detect anything ?

### ISSUE THREAD

**Issue by TheWolfbane** [rembound/Arena-Helper#84]
So I dont have a clue whats wrong. 

Some other people seem to have problem "detecting" But mine does not evne get to that part, its grayed out and cant move the window, let it be for several minuts and still nothing happens, and onyl way I can shut down the program is kill it in "Task Manager"

http://prntscr.com/azfah7

Its like the entire window freezes, cant move the window, cant do anything with it.

**Comment by rembound** [comment]
An old version had this problem due to a HDT update. Try installing the latest version of Arena Helper.

**Comment by TheWolfbane** [comment]
Yes downloaded the latest version, and it solved the problem, thx for fast reply. 

Any future plans to implement a "check" for new version ?

Keep up the great work

**Comment by rembound** [comment]
There is actually a version check already.
Thanks!

**Comment by TheWolfbane** [comment]
And how is this check triggered ?

Since It did not tell me to update so its not automaticly. 

I did search for a "Check for update" dint find any.
so Im guessing I must have missed it. 

Unless its auto and was implemented in the version I did not own.

**Comment by rembound** [comment]
When you start up the plugin, the update check is done. Your older version probably didn't have it yet.
