### ISSUE TITLE
GDI+ problem

### ISSUE THREAD

**Issue by Freeze2312** [rembound/Arena-Helper#85]
Arena Helper can't detect heroes.

**Comment by Freeze2312** [comment]
![default](https://cloud.githubusercontent.com/assets/19172251/14990231/4644efc8-1164-11e6-9871-666f4a1bf7aa.PNG)

**Comment by Freeze2312** [comment]
In english that means "A generic error occurred in GDI+"

**Comment by rembound** [comment]
I've never seen this error before, but the image shows me where the error occurred in the code.

Try this version of the plugin with the `ShowBitmap` removed:
[ArenaHelper.v0.7.1-nobitmap.zip](https://github.com/rembound/Arena-Helper/files/248439/ArenaHelper.v0.7.1-nobitmap.zip)

**Comment by Freeze2312** [comment]
Thanks, nobitmap version works correct.
![2](https://cloud.githubusercontent.com/assets/19172251/15020178/9bcbb38a-1229-11e6-8d9c-232813f4a926.PNG)
