### ISSUE TITLE
Wrong card showing

### ISSUE THREAD

**Issue by kaganb** [rembound/Arena-Helper#87]
Had a discrepancy in drafting.  It shows Fandral Staghelm while Nerub'ar Warlord is the actual card for a Warlock run.

![image](https://cloud.githubusercontent.com/assets/19510060/15450988/4bbe0d9c-1f7c-11e6-928a-ec54d6ca0ce0.png)

**Comment by rembound** [comment]
I think this is because the cards are visually similar in shape. Detection is never 100%, so there is always an error rate. Thanks for reporting the issue!
