### ISSUE TITLE
Automated created deck name time

### ISSUE THREAD

**Issue by FoX-Sempai** [rembound/Arena-Helper#88]
There is a bug with time in automated created deck name. Can author use 24 hours format instead of 12 hours? Or add it in options pls. Or... at least add "am" or "pm" in name.

**Comment by rembound** [comment]
The deckname uses a setting of Hearthstone Deck Tracker. Go to the HDT options and enable `Advanced options`, go to `Tracker -> Importing -> Arena Deck Name Template`. Change the format to your preference.

**Comment by FoX-Sempai** [comment]
Ah, thanks a lot! Sorry for silly issue.

**Comment by rembound** [comment]
No problem!
