### ISSUE TITLE
Help! cannot detect arena

### ISSUE THREAD

**Issue by garythy** [rembound/Arena-Helper#89]
![untitled](https://cloud.githubusercontent.com/assets/12252377/15649625/852ac450-26a5-11e6-9687-12fdb17d947c.jpg)

**Comment by riQQ** [comment]
Looks like an installation problem, see https://github.com/rembound/Arena-Helper#how-to-install.

**Comment by sdbds** [comment]
i think HDT new version 15.0+ cant use Arena-Helper。

**Comment by rembound** [comment]
Arena Helper seems to work fine on 15.x. Make sure you have followed the installation instructions like @riQQ posted.

**Comment by sdbds** [comment]
i got it。in 15.0+ i need to Fullscreen HS to use it，if i windowed HS，it cant detect arena。

**Comment by rembound** [comment]
Also check out [this comment](https://github.com/rembound/Arena-Helper/issues/90#issuecomment-223758125). Maybe some settings or methods changed in the new HDT version.

**Comment by garythy** [comment]
It's working now! needs to be in windowed mode. Thanks!

**Comment by tknights2015** [comment]
Not working for me with new HS update. Finds the hero and sits on detecting arena
