### ISSUE TITLE
Arena Helper not detecting cards HDT version 15.2

### ISSUE THREAD

**Issue by tknights2015** [rembound/Arena-Helper#90]
Arena Helper is not detecting cards at all since HDT update to 15.2
Also did not deck heroes until after one was selected.
![arena helper](https://cloud.githubusercontent.com/assets/16232528/15698583/3c8fd2ec-2783-11e6-998f-8d466dcb19f3.JPG)

**Comment by rembound** [comment]
Try using a standard resolution like 1920x1080 or similar. Arenacheck1 should be below 10 if it works correctly.

**Comment by tknights2015** [comment]
Arena helper was already installed and working perfectly until the HDT update.  Also nothing has changed on the resolution on monitor or game.  Why would I need to change resolution or follow install instructions when all already installed. Is there a new version in the last few days of Arena Helper?

**Comment by Paschouale** [comment]
Try it on window screen i had the same problem! This seems to fix it! It needs to be below 10 as rembound says! Do it just to see the stats and the fullscreen it again!

**Comment by tknights2015** [comment]
And now, it is not detecting cards again. no updates and will not work even at full screen

**Comment by tknights2015** [comment]
Any updates for this issue?

**Comment by rembound** [comment]
I don't know what causes this issue. Nothing changed in between.

**Comment by tknights2015** [comment]
I even uninstalled Arena helper and re-installed. Does not detect cards or class.  Tried changing resolution, full screen.  Same as the screen shot above. Disappointed that I can't use the plug in  anymore.

**Comment by rembound** [comment]
This looks like the same issue that you've already seen at https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/1889 and https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2034

Try this version that uses the screen capture method that was set in the HDT settings:
[ArenaHelper.v0.8.0-alternative.zip](https://github.com/rembound/Arena-Helper/files/336791/ArenaHelper.v0.8.0-alternative.zip)

**Comment by tknights2015** [comment]
I had to completely uninstall Arena Helper and install again to get this to work.  Working correctly as of now
