### ISSUE TITLE
Get stuck every time

### ISSUE THREAD

**Issue by occurrence** [rembound/Arena-Helper#91]
I really like this plugin, but I have a problem that occurs every time I make a new arena deck. I choose new arena and when I select the hero, the hero is highlighted in the plugin, but then when I am prompted with the cards it is still in the hero selection part.

So then, I choose hero manually and then it calculates the three cards, but then a new problem occurs. When I select one of the cards it gets stuck again, so when the three new cards are being displayed it still shows the stats for the previous selection. So then, I have to restart HSTracker and do it over again. Then it usually works until I have completed the deck.

**Comment by rembound** [comment]
This is an issue with HDT, out of my control. I haven't experienced this problem with the latest version, but have seen something like this in the past. It has to do with the logreaders as I have commented on here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2165#issuecomment-191170183

Try restarting HDT and Hearthstone before starting a new arena run and using the plugin.

**Comment by morkraw** [comment]
I still have this issue (or a very similar one) and the corresponding issue on the main HDT repository is marked as closed. 

This seems to happen reliably if hearthstone is closed and restarted, and requires a restart of HDT to restore functionality. I am guessing this is still something you have to bounce back up to the main HDT dev but as I said the referenced issue is marked as closed, so presumably it will not be looked at as things stand.
