### ISSUE TITLE
uneven permission

### ISSUE THREAD

**Issue by oxyd1n** [rembound/Arena-Helper#92]
it appears that HSt (batleNet) and HTD do not have the same permission.
Please run both as admin or local user.
If you don't what any of this means, just run HTD as admin.

what to do?

**Comment by oxyd1n** [comment]
ArenaHelper.v0.8.0

**Comment by riQQ** [comment]
Right click the HDT.exe or your link to it and click `Run as administrator`.

**Comment by oxyd1n** [comment]
doing so does not give an error ... just hanging out "detecting arena " and nothing happens

**Comment by riQQ** [comment]
>The aspect ratio of the window could be messing with the detection. The plugin doesn't support all aspect ratios. Try to set the window to a 1920x1080 or similar resolution.

https://github.com/rembound/Arena-Helper/issues/39#issuecomment-154525530

**Comment by oxyd1n** [comment]
hardstouna window or HDT?

**Comment by oxyd1n** [comment]
I have a laptop. In the game there is only 1280 * 720 , 1366 * 720 and 1368 * 768

No 1920 * 720 ( ( ( on a laptop , too

**Comment by oxyd1n** [comment]
tried it does not work, do not know what to do (((wanted to try a computer with WinXP. It does not start at all HTD

**Comment by oxyd1n** [comment]
tried in different ways, it does not work ((apparently no luck ... at WinXp not start (("not yavletsya application win 32"

**Comment by oxyd1n** [comment]
Why then hardstoun settings in the display settings are reset. There is no - an empty string

**Comment by riQQ** [comment]
HDT doesn't work on Windows XP.
Do you use windowed or fullscreen mode? Try fullscreen and then setting the resolution.

**Comment by oxyd1n** [comment]
I tried in different ways. And in windowed mode and in full. I change the screen size. Still does not work "Arena helper". 
what is wrong, I do not understand?

**Comment by riQQ** [comment]
Do you use any screen dimming software?

**Comment by oxyd1n** [comment]
I do not understand the question ... for example?

**Comment by riQQ** [comment]
Software like [f.lux](https://justgetflux.com/).

**Comment by oxyd1n** [comment]
no additional software

**Comment by RtwoDtwo1** [comment]
I have the same issue, run it as administrator and it still throws the same error. Restart PC and it seems to work alright for a while but close it out and open it again and its back to not working.

**Comment by riQQ** [comment]
@RtwoDtwo1 not an Arena Helper issue, your issue is tracked here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2738.
