### ISSUE TITLE
Card picks don't update

### ISSUE THREAD

**Issue by chouithegewy** [rembound/Arena-Helper#93]
Hello, guys. So after I make a pick I have to re-select mage (or whatever hero I'm playing) to get the values to update to the next pick selection. Otherwise, the values of the previous pick remain. I have to do this for every pick. Wasn't like this before. Stopped using the Arena Helper a month or so ago. Just came back to it recently.

Pretty annoying.

Help is appreciated,
Chilos

**Comment by chouithegewy** [comment]
Manual selecting seems to work, but it's more time consuming.

**Comment by rembound** [comment]
This is a known issue with Hearthstone Deck Tracker, but make sure to always update to the latest version. See my comments here: https://github.com/rembound/Arena-Helper/issues/91#issuecomment-231531824

A workaround is:
> Try restarting HDT and Hearthstone before starting a new arena run and using the plugin.
