### ISSUE TITLE
Deck rating

### ISSUE THREAD

**Issue by Werwolfsoul** [rembound/Arena-Helper#94]
I'd like to see the deck value after I complete all picks. it's can be sum values of all piked cards or average value of all picked cards. it will be useful for statistics
thx anyway

**Comment by rembound** [comment]
I have been thinking about an overview/stats page with your previous decks and their scores. Maybe in a later version.. Thanks for the suggestion.

**Comment by rembound** [comment]
Added the deck average in the new version.
