### ISSUE TITLE
plz add new function such as total value and Average

### ISSUE THREAD

**Issue by sdbds** [rembound/Arena-Helper#97]
we all know each card has its independent value with HATL。
can we watch total value and average deck clearly？
we can mark deck with general value like 80 or 30(cards)*60(average)=1800？

**Comment by rembound** [comment]
Thanks for the suggestion. As with a similar suggestion https://github.com/rembound/Arena-Helper/issues/94 maybe in a later update.

**Comment by rembound** [comment]
Added the deck average in the new version.
