### ISSUE TITLE
Plugin dissapear with no error msg

### ISSUE THREAD

**Issue by sinpro2694** [rembound/Arena-Helper#98]
I have followed the installation steps.

When I launch decktracker arena helper just dissapear from \Hearthstone Deck Tracker\Plugins folder, with no error message

I'm using the decktracker version downloaded from github (no windows install)
Using this plugin https://github.com/rembound/Arena-Helper/releases

**Comment by rembound** [comment]
Make sure you install the plugin to the correct directory. HDT has recently changed the plugin folder behavior, so plugins need to be installed in a different directory.

See [How To Install](https://github.com/rembound/Arena-Helper#how-to-install) in the readme:
> Unzip the archive to `%AppData%/HearthstoneDeckTracker/Plugins` To find this directory, you can click the following button in the Hearthstone Deck Tracker options menu: `Options -> Tracker -> Plugins -> Plugins Folder`

**Comment by sinpro2694** [comment]
Using the path %AppData%/HearthstoneDeckTracker/Plugins solved the issue. 
Thank you
