### ISSUE TITLE
Update is taking too long

### ISSUE THREAD

**Issue by TemporalOnline** [rembound/Arena-Helper#99]
With the new HDT, Arena-helper tries to update itself upon HDT splash... which makes the whole thing take about +20 secs than normal.

Can you do something about it on your end?

Thanks.

**Comment by rembound** [comment]
Arena Helper only gets the version information from GitHub when it loads, which are two small text files. It doesn't download and install any big files without user interaction. It shouldn't be locking up HDT.

Try disabling the plugin and restart a couple of times. Then, enable it again to see the difference. It most likely is something else in HDT. HDT also has syncing with Hearthstats which could be causing delays.
